// app/routes/work.tsx
import type { MetaFunction } from "@remix-run/node";

export const meta: MetaFunction = () => {
    return [
        { title: "Andrew Lee - Work" },
        { name: "description", content: "Andrew Lee - Work" },
    ];
};

interface WorkEntry {
    title: string;
    company: string;
    image_url?: string;
    colorClass?: [string, string];
    dates: [Date, Date];
    bullet_points: string[];
};

function WorkEntry({ entry }: { entry: WorkEntry }) {
    return (
        <div key={entry.company} className="flex flex-row">
            <div className="flex flex-col items-center mr-5">
                <p className="italic !my-1">{entry.dates[0].getUTCFullYear()}</p>
                <div className="w-8 lg:w-14">
                {entry.image_url && <img src={entry.image_url} alt={entry.company} className="rounded w-full !my-1" />}
                </div>
            </div>
            <div className="border-r-4 mr-6 mt-3 -mb-3 border-slate-300 dark:border-slate-600">
                <div className="absolute ring-4 ring-slate-300 dark:ring-slate-600 w-3 h-3 -ml-1 rounded-full bg-base-100">&nbsp;</div>
            </div>
            <div className="flex flex-col flex-grow mb-4">
                <h2 className="!mt-0 !mb-4">
                    <span className={`border-b-4 ${entry.colorClass && `${entry.colorClass[0]} ${entry.colorClass[1]}`}`}>
                        {entry.title}
                    </span>
                </h2>
                <h3 className="!mt-0">{entry.company}</h3>
                {/* <h4 className="italic">{entry.date}</h4> */}
                <ul>
                    {entry.bullet_points.map((point, index) => (
                        <li key={point}>{point}</li>
                    ))}
                </ul>
            </div>
        </div>
    )
}

export default function Work() {
    return (
        <div className="flex flex-col items-center mx-4">
            <article className="prose max-w-none">
                <h1 className="text-center mb-8">⚒️Work</h1>
                <div className="mt-14">
                {workEntries.map((entry) => (
                    <WorkEntry key={entry.company} entry={entry} />
                ))}
                </div>
            </article>
        </div>
    )
}


const workEntries: WorkEntry[] = [
    {
        title: "Software Development Intern",
        company: "Lucid Software - Data Infrastructure Team",
        image_url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAkFBMVEUoLTP///8oLTEoLDVHTFImLTP///0pLDEpLDPZ3eApLjJaXmErMDYkKS8nKi/8/PxXWFwsMDne3+P6+/8hJiwwMzgkKDE3OD0jKCxbXmOJio4vNDopKi66u7+YnJ8oLC3y8/dwcXPS09esrbFpam9RUlZCQ0fm5+l/gISytbqUl5x2d3vIyMo4O0Dz9fTu7fKdv4/FAAAGM0lEQVR4nO2ci3baOBBAZRszAkYyfsiY2EnzImkb0v7/363kBykJSbeLKaPsXHIO52ACuhmNZEcji4n4JLAINViEGixCDRahBotQg0WowSLUYBFqsAg1WIQaLEINFqEGi1CDRajBItRgEWqwCDVYhBosQg0WoQaLUINFqMEi1DitSHTST99jbJHQ4p6jMk3juExBA0ipRGSdpAQY+eteOJlIWlqVKAJjCokKvRVRtvFpGSFUzXoi0d+ICBSIIi3g4S5fS6W8E4kt7hkr0IWWq4ufQbCBGruj/omE2hhAc58FeZ7cQ9Ef9U4kDG1uwOYyCBL7s64QR/6at5xExObJfP5wlQd54H42iGrkr3nLaCIKa6Fcjqu6Ck3VXDwGiQ2HYzEMAKdkLBH7Ry+EzWllPeZheJPlXbdyImufRIaIaKPnZnKZ23BYien0RWQYz07EaCIo3NCEEIYrmxwdySACHok4FeEi8vXRJng+nVqLFpcjEMY9433dK8bLkTbRYX3rYpAHbSiCaRuTxRePRATaXC8m3/I2w9scb/uVbyISbZab79cuO5xHMu3TpOtaoQciNhKIRdM08JQFQ5bv041a0Wmvso4VUXbyKKSBZrkNkoMaw4RIXMQmeGF0Y0/Wg3w3lfsoIkRdF88X13nXq6YeiwhltkF3PuJ1ROyVINwG+XWXIQdNvBBRtRKmP0MMgh8eR8SeLcIsaYNhe5a/OeKaB7ODgfBOJAw/lch0erBb+SMiOpEpi4zESCJTFhmL40Xmn0NEdCIfwiJ/AovsYJFxYZEdLDIuLLKDRcaFRXawyLiwyI7/qYhsAQh79hd/jpBlkf8o8kInYl8ep8udWUR8ApGRYZEdfybyskwdOYTNe5ByBM1zi4DfIq5sBZWopcTnq6Us0s5KHFEO9bdFlLVoZ47aPoraPD262s3SP5G+5nGuAbSB5TYPkiVg5KcI1vMQtQ4nd+3hZQEeinQ1g6Cb5vn7z8DVEuVLAx52rdZljvPmxv2SqxZ0EUlT70TSSKAuVpttt549nQb5wkak9EWkmzbsu9Gd+U7ukqCtMWgXVZYakHJEprvFn0Uo3FaSskwlNKYxF497b1zaKfHoVvwVkbW96kjTMq0L2TTVTRbs16wsR6mYP2XX+lWkjKMykiVstknyqq7LIxGwXSuNUFbPV9dv30ZfZFBxNY2oFJqvP/sSVM8iMogsGgjtXL647evlE/9EOhZfYF49XPYlqImPEdmJGJcc+VDavF9n54NI1+x7czPMHIeKCmiLJLvnJLjYDq8erI6gKfLSVJcLLi2urx6TrkT7nTIP2iI/+tEp/zZphlJzz0SGxrYT+Pa+Cud+i7hwPD6t7NEwy19LeiIyqFytvjRhuNLeRqRr7eXEnrKDRg1ZP4a9U9JFRQSg+eXE3LXV9arb+wZQSemqUGcfWDiR+W6jDBWRpKvIDvLrixVILCN34SfC7P1uRU8k2WkkeX63qgBQRPZqKook/HuRs17q9hEJgmGX2OWmAQDtbo9gQyI8E+lH2DyY3ZhGm0LWNWKs2t34vxNxyT7suj67SJcbLjlKkLJwO5YK1zjr8dscISLSDb+5tQjyuwcsIhG5zZWIdaxUDL3n70XcZ51ZpN12YT2267mWkUtwZVViFdvO5dY/2oBRF1G1Cs3MZcjsyWgD3fpNFA0LOqBBZ+9sWRpEBKpuqeGYWykcvX1PKdRuj9X3Zzvk2oDsi4gKUGcfWNg/wRLbZZMzixRxrXSWf3swGlxqDCLDcRNqczmbzbIsmx0iy243KNw/sY+83cixIjaja7xbI4Lbsy7Ua5EqRI0GVmY+gL8+UJtnrdD9E/vMIgqLwlQrrbVAEafp6+O269Wqlhp2VRti72GgkALL80ckxhorA5Vrgu3ob+624fo+ugqUQeMVbk0XVRfD84oUNk9sc7BSmMZx2peYhF3xjBRuCLYNdcu4B09BZHtfofT8XStN7dgp7BgLtY1Iql6L2BdrJdKym7sPiKDrWOn5I0IGFqEGi1CDRajBItRgEWqwCDVYhBosQg0WoQaLUINFqMEi1GARarAINViEGixCDRahBotQg0WowSLUYBFqsAg1WIQaLEINFqEGi1CDRajxWUT+AZd4aHmhwyNEAAAAAElFTkSuQmCC",
        dates: [new Date("2023-05-15"), new Date("2023-08-15")],
        colorClass: ["border-blue-400", "dark:border-blue-600"],
        bullet_points: [
            "Designed and built a new dashboard for monitoring user events & metrics, including tree-based action tracking.",
            "Implemented flow-based math operation shapes in LucidSpark during a hackathon.",
            "Fixed bugs and added features to internal data infrastructure & reporting tools.",
        ]
    },
    {
        title: "Software Development Intern",
        company: "InfluxData - Edge Team",
        image_url: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIHEBMQEBAVEREREBEWFhYVEBYQFRISGBUZFxgXGRkYKDQhGx4mHhYWLT0hMSkrLi4wGCs1Oj8tNzQuLywBCgoKDg0OGBAQGy8gHSAwNy0tLTctLSstLjcrLS0tLSstNzctKy0tLS0uLS0tLS0tLS0tLy0tKy8rLS0tLS0tLf/AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAwADAQEAAAAAAAAAAAAABQYHAwQIAgH/xABEEAABAwIDAwgFCgQFBQAAAAABAAIDBBEFBhIhQVEHEyIxYXGRoUJScoGSFBUjMmKCorHB0bLC4fAzU5PS8SUmQ2OE/8QAGgEBAAMBAQEAAAAAAAAAAAAAAAECBAMFBv/EACwRAAIBAwMBBgYDAAAAAAAAAAABAgMEERIhMVEFEyIyQWEUM3GBkbFSofD/2gAMAwEAAhEDEQA/ALqiIvSPiQiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIuCtrY6Bhkme2Ng6y42CEpN7I50XWw7EYsTZzkEjZGXtdpvY8DwXK2oY5xjD2l7QLtDhqHeFJLi08M5ERFBUIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIijMwY5FgMJllPENaD0nu4D91JaMXJ4XJy4zi0WCxOmndpaOr1nO3NaN5WI5rzPLmSTU/oRNPQjB2N7Txd2rgzJmGbMMvOSnoi+hgPRY3gO3q2qJXSMcHv2lmqS1S836JrKuYpMuzCRm1jrCRl9j2/uNxWk5lwaLONO2sonfTtb0SDpL7bSx/Bw3fsscViyZmh+XJb7XQPI5xl/wATb+kPNGvUvcUG33lPzL+zloc6Yhg7ix0rn6TYsmGsgjcSekPFWzC+VSN9hU05Z9qM6h8LrW8SuznPLUeZ4RW0dnSlt+j/AOZvVbb6Yt+iyR7SwkEEEGxBFiCmEznCnQuI5aw/U9A4XmejxW3NVDC4+i46HX9l1iVLrzMpfC80VmFWEVQ8NHok62fC64UOHQz1Oy/4P8noJFluF8qj2WFTTtePWjOg/Cb38QrfheeKHEtgnEbvVlHN+f1fNVaaMNSzrQ5RY0QbUVTKEREAREQBERAEREAREQBEVezdmuLLjNvTncOhHf8AE7g387KeS9OnKctMVudjM+ZIcuxa5DqeR0Iwek8/oOJWH45jM2OSmWZ1yeoeixvqtG4LixXEpcWldNM8ue4+4DgBuC6i6Rjg+htbSNFZ5YREVzWEREBasjZtdl6TRJd1NIekN7D67fDaN6tuecnjHGitobOe9oLmtIAmb1h7ftdm/v68tpaZ9W9scbS97yA1oFySt7yhhT8Fo4oJHXe3UTY3DS5xOkd11zlseZeNUZKpB4l+zFocr1sztIpJr9sTmDxNgFPUHJnW1G2Qxwjfqfqd4MuPNW7Pedn5ekbBDG1zywOLn3IAJIAAFtuxZ9X54r67rqHMHCMCK3vbt81KbZ0hUuKsU0kky4wcmlLQjXV1Zt9yBvi691yc/gWB/VDJXjgHVNz3uu1ZZPUPqDqe9z3He5xcfErjTT1L/Czl55t/TY1Os5VYmG0NK5w4vkEfk0FXbAMWZjlOyojBAfe7T1tcDYjYvOy1jkdrecgmgPXHIHjueLfmzzUSikjJeWdOFLVBcGgoiLmeOEREAREQBERAEREJKtnXODMut0Ms+ocNjdzB6zv23rFq+skxCR0sry97zck7Sf72Ls5gppqSpkbU357WS4nbqub6geBuo9dorB9Ja28KUMrdv1CIisagiIgC7GH0MmJSNihYXvebAD+vUO1cuD4VLjErYYG6nnwaN7nHcFqsUdJyc0t3ESVMje58juA9Vg/vaqtmevX0eGO8nwj8w7DaXk+pufnIfUuba+9zvUj7OJ/4VJjzpUVdfFUSSFsbZWjQ1xDGxE9IW37N5UJjeMzY3KZp3XJ6h6LG+q0bgo8KFHqUp22zlU3k/wDbGkcslFZ9POB9Zr4z7jqb/E7wWbrWc2n57wOKfrcxsMh9ofRv8yfBZMpiRZSfd6Xym0ERFY2BXXkmrfk9dzZ6pont+83pjya7xVKUjlyt+b6uCa9gyVhPs36XldQ+DlXhrpyj7HohERcD5YIiIQEREAREQBERCSmYvh9Pn+m5yE6J4iQNQs5jt8cgG4/3vWQV1I+gkdFK0skYbEHrBVqxLEZcoYtO+L6plLnM6mvjf09PnsO5W/HsHgz3TNqqUgTtbYbiTvifwPA/oV0W30PcpTdDGfI+PYx9F9zwup3OY9pa5pIcCLEEbLG6+F0PSCksAwObHpRFC2+9zj9VjeLiufLGXZcxTc3GLNG17yOixv6nrsFo2LYrS5ApxT0zQ+ocL2Jub/5kh/Ifkqt+iMtau4vRDeTPqoqaTk5pubZ9JUyC9vSkd6zvVYNw/qVlOK4lLi0rppnFz3H3AcANwXxX1smISOlleXvebkneuuiRahQVPxPeT5YREVjQazyfH53wmelPW3nmDsD23afiJ8Fk7hpJB3K/8jtbzVRNCTskiDh7TD+z3Kr5xovm+uqI7WAlc4Dg1/THk4Ki5Zio+GvOHXch0RFc2hAiID0Plut+caOCW9y+Fl/aAs7zBUkqVyTVnyihMZO2GVwt9l3SHmXK6rg+T5a4hoqSj7hERQcQiIgCIiAIiIDJeWCi5qpimAsJYtJ7XMP7Oaq5lLMkmXJtbbujdYSMvsc3j7Q3FaNyt0XP0TZQNsMzbng1w0nz0rHV1juj6Gzaq26jL6Gt5sy9Fm+nFbREGbTfZs50D0XcHj+nBUvL2SqnFZtEkb4Y2npvewtsODQesrvcleLSUtYKcEmKcPu3cHNYXBw+G3/C2Qmyq21sZatepbZpLdehQsx5hgyVCKOia3nre0Gbtb+Lzw/SwWT1NQ+re6SRxe9xuSTck+9aFj3JnO975IJxNqc51pOi/ab/AFtoce3YqZimX6rCv8eB7B62nUz4m7FaODXaOil4XlvnqRiIiubQiIgJ3I1b8gxCnfuMmg9z+h/N5Kf5X6LmauOYDZLFbvcw2PkWqixvMbg4GxBBHYVqvKYwYphtPVNHUY3dzJWbfPSqPlGKt4K8JddjKERFc2hERAaByO1vNVE0N9kkQcPaYf2e5aysDyNW/IMQp37jJoPc/ofzeS3xcp8ng9pQxV1dQiIqHnBERAEREAREQEXmmj+X0VRFa5dC8j2mjU3zAXnpemV50x6i+bqqaHdHK9o9m/R8rLpA9jsue0o/cuHJDhvP1MlQRshjs3237P4Q7xULn7F3YnXS2cSyJ2hgvsGnYSO9wJ96vWUgMuYM+pdse9skvvPQjHv6Pisic7USTtJ81K3eTTRXeVpz6bIncLzjW4XYMqHOaPRf9K3u6XV7lb8L5VL2bVU/e6I/yu/3LMkUuKO07WlPlGv3wXNH+WyR3/zPufAOPio3E+SsG7qWo7myN3e23/asyUlhmP1OFf4E72D1dV2/CdhUaWjj8NUh8uf2e53MUydW4Xcvp3OaPSZ9I3v6PV71AkEdYWgYXypTw2FRCyUcWnmnfqPIKeGYsIzLsqGNY87PpWaHf6jerxTLXJPf1oeeGfdGQrWcB/65gEkR2ujjlb95h5xn8vguOt5NKWvGukqC0Hq2idnuI2+ZU5kTLUuXIpY5pGPEjwQGXIAtbbqA6+HYobTRwubmnOCae6aZhxRXat5NqxszmxBjotR0vMgA032XHXf3KToOSlx2z1IHZGwu/E635K2pGt3lFLOozZfrWlxsBcngtfGUMJwTbUPBI2/TTgE/dba/gvoZxwvCTppY9TuoCCDSSeq1za/mo1HL43Py4Nme4JlOtr5GaIHxjUDre0xtbt+td3X7lvK4aKZ1RG174zE5wuWOILm9htvXMqN5PJurmVZrKxgIiKpkCIiAIiIAiIgCx/lFwcy4qxrBtqxFbhqJ5s/wg+9bAo2twaOsqYKl31qcSWFtjtQtt7lZPBpta/dTz7Mp/KrVtw+jgo49geRs/wDVELAH3lvgsoVr5TMS+cK97QbtgaIh3ja78RI9yqi6RWEe7aQ00lnl7hERWNIREQBERAdmir5aB2qGV8Z4teW/ktd5M8fnxuGUVB1mJzAH2ALg4HYbcNPmsZWuYB/2zgbpzsfIx0g9uToR+WgqkjBfwi4JY3bwiLzPykSxyviow1rGOLeccNbnEbwDsA8VTq/NFZX35yqkIO4O0N+FtgogrlpKV9Y9scbC97zYAC5JU4SNFO3pU1sj5ijdUODWguc42AG0uJ2blsGRcjtwcNqKgB1QRcN62w/u7t3buK7OSsmMwFollAfUkbT1tiv6Le3tVtVJS9EeXeXurwU+AiIqHlhERAEREAREQBERAEREJMFzRl6qw6aV0sbnNMj3c6GlzXXN73HV3FQC9MqFxTKlHilzLTs1H0mjm3d922v710Uz16XaaSxNfgwBFqGKclTXXNNUEfZlbcfG39lT8UyVXYbcugL2j0o/pR+HaPeFZSRvp3VKpwyvov1zS3YRYjyX4rGgIiIDt4TRHEZ4oR1ySNb3XPWtH5W60UkEFGzYCdRA3MYNLR5n4VC8kuHfKqx0xGynjJHtv6I8tfguPNcUua8Vkhgbq5siMeqxrNjnE7hqLvFUb3MNRqVws8RWSqYbh8mJyNihYXvcdgH5ngO1bZk3KUeXI7mz6hw6b+H2WcB+a58p5Ziy3Fpb0pXAa5LbXHgODexTqrKWTz7y9dTww8v7CIioecEREAREQBERAEREAREQBERAEREAREQHQxPBKbFRaeBknaW2d8Q2qoYryXU89zTyvhPB30rPOxHiVfkUps707irT8sjEsV5Pa6guWsE7RviNz8JsT7rqr1FO+mcWyMcxw62uaWke4r0quKemZUW1sa+x2amh1u66spm6n2pJedZKpyXYWcPog9ws+oeX7Rt0dTP1P3lPYHgcOCNc2IEue4ue9x1Pe7tKkkVWzBVrSnKT6hERQcQiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiID//Z",
        dates: [new Date("2022-05-01"), new Date("2022-08-01")],
        colorClass: ["border-cyan-400", "dark:border-cyan-600"],
        bullet_points: [
            "Implemented features and fixed bugs for InfluxDB, the open-source time series database.",
            "Built a new InfluxQL shell with features like fancy tables and command autocompletion.",
            "Designed a proof-of-concept visualization for geo-temporal data on a 3D globe."
        ]
    },
    {
        title: "Machine Learning Intern",
        company: "VPI Technology Group",
        image_url: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPEBAQEBASFRUVFRUQEBUVEA8VEA8VGhgWFxcXGBcYHyggGB8xGxUYITEiJSkrLjoxGB80ODMsNykvLisBCgoKDg0OGxAQGi0iICUtLS8uKy43Li0tNy8tLS0tLSsrLTc1NS0tLjAtLS0tNy03Ny0tLTAtLS0tLS0tKy0tLf/AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABAEAACAgACBgcFBQcCBwAAAAAAAQIDBBEFBiExQVESEyIjYXGBBxRSsdEyQpGh8BYzU2Kj0uGiwSQ0cpKywvH/xAAaAQEAAgMBAAAAAAAAAAAAAAAABAUBAwYC/8QALBEAAgIBAwMBBwUBAAAAAAAAAAECAwQREjEFE0FhFCEiUnGRsTJCQ4Hw0f/aAAwDAQACEQMRAD8AvEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFea0aX0jgrnHrs65Zyql1VW1cn2d6zON+2eP/jf06v7SytPaJhjKZVT374Sy2wlwa/XMpzHYSdFk6rFlKLyaLfE7VsdHFaooM9XUz1jJ7X/tDs/tnj/439Or+0ftnj/439Or+0j4Jfs9Xyr7ED2q7539yQftnj/439Or+0ftnj/439Or+0j4Hs9Xyr7D2q7539yVaL13xUbYO+anXnlNdCCeXNZLhyLNptjOMZRaaklKLW5p7UyiCdez7T/Rawlstj20t8HvcPp6+BCzMVbd0FwWPT82W7ZY9deCwgAVRegAAAAAAAxmAZB5QujJtRkm1saTTy88j0BhPUAhutus+JwdnVwqh0ZLOE5OUulz2LLJp/NEQxetWNt33yiuUEofmtpLqw7LFuWmhAu6jVVJxeraLdtvhBZzlGK5tpI4+L1swVW++MnygnP847CpLrpTec5Sk+cpNv8AM8yXHpy/dIgz6vJ/pjoWLi/aJUv3VE5f9TjFflmcXFa/YuX2FXBeEXJ/myKM85SJEcOqPgiyz75/u0+hd2gdLQxlEbYeU48YS4r9czBWWoOmXh8XCtvsXd3JcOlt6D/HZ6gqsmjtz08F5jZKsrTfJb5EdfNAdfX7xWu8rXaS32Q+q3/iS4Gmux1yUkb7qo2wcZFCAlOvOgPdreurXdWPhurnxXk969fAix0NVisipI5O6qVU3CXgAA2GoH1CTTTTaa2pren6btp8gcmU9PeW5qhp1YyntNdZDKNi58pJcnl8zvlKaD0pPCXRthw2TjwnHZmvyLjwGLhfXC2t5xks0yiy8fty1XDOlwMrvQ0fKNg8r8RCtdKc4xXOUkl+LPHSeFd1M64zlCTXZlFtSi+D2FM6SqthbOFzl04vKXSbb/F+BjGx1c+dD1mZbx0vh11LUxet2CqzzuUnygnLP1Wz8ziYv2iVr91ROXjOSj+SzzK8BYQwK1z7ypn1S6XGiJRi9esZP7DhWv5YZv8A1ZnExelsRd+8vsl4Ob6P4LYaQJMaK48IiTyLZ/qkzr6s6alg71Pa4Ps2x5x5+aLgoujZGM4NOMkpRa3NPcUQTj2fawdB+6WvY3nS3918Y+vDxz5oh52PuW+PgsOm5eyXblw+PqS/WLQ8cZRKt7JLtVy+GXD0KdxNEq5yrmspRbjJcmXsQr2gaA6yPvVa7UV3qX34fF5r5eRHwsjY9j4ZK6lidyPcjyvwVyAYky5OfMSZr2zPqyZp2zzCNsUbuhZN4vDZb+uqy8+nEwdP2fYB36Qp2bK++m+XR+z/AKnH8wVmbcoz00TLjEx9Yal4gAqi4NTSWChiKp1WLOMlk+a5Ncmt5TemNGzwt06Z719l8Jx4SRdxHdctA+909KC72Gbh/OuMf1xJmHkduWj4ZXdQxe7DdHlFTAy01sfkzBeHNgAAwCWah6f6izqLH3dj7Le6uf8AsmRMGu2tWRcWbqbpVTU4l9kQ190B19fvFa7ytdtLfZD6o9NRdP8AvFfU2Pva1x32Q4PzW5krKL46LPVHTfBlU+jKEBKNeNAe7W9bWu6sezlXPjHy4r/BFy9rsVkVJHMXVSqm4S8AAGw1AzGTTTTya2pren/sYAM8Ft6n6dWMpyk+9hlGxc+UvX55nfaz2FKaF0pPCXRuhw2SXCceMS5MBjIX1wtrecZLNfR+JR5eP2parhnS4GV3obZcoq3XTQLwl3Sgu6sbcOUHxj9PDyIxOReemNGwxVM6Z7pLY+MHwkijdM4SzDWzpsWUovJ8pLg14Mn4V/cjtfKK7OxO1PdHhmnbYeD5Le9iQkydezDVrrrPfbo9iDypTX25r73kvn5Em61VwcmeMahzkiX+z/Vv3HD9Kxd9blKznBfdh6Z7fFswSwHO2TlOW5nRQgoR0QAB5PQAABXHtA0B1cveq12ZPvUvuy+L1+fmQovbE0RshKE1nGScZJ7mmU7rHoeWDvlW83F9quXxR+qLjByNy2S5Rz/UsTZLuR4f5OWACwKkAAA2NH4ydFkLa3lKLzXJ80/Bly6F0nDFUxthx2SXGEuMWUkSDU/Tzwd2Un3U8lYvhfCXp8iFmY/cjuXKLHp+V2p7ZcMtHSeBhiKp02LOMlk+afBrk0ym9L6Onhbp02LbHc+E1wki7IyTSa47V4ke1z0D73T0oLva83D+dcY/TxIGJkdqWj4ZaZ+L3obo8oqcGWstj9TBeHNgAAwGyVaiaw+729Ra+7sext7K58/J/Qicma9szXbWrIuLJGPZKqamj9CkO9ourXvdPXVR76pZ5JbbYb3HzW9evM2PZ5pt4vC9GbzsqfVyfGS+5J+mz0ZKSh1lRZ6o6f4L6/Rn5/1Y0HPSGJjTHNRXatl8EOPrwRfOCwsKa4VVxUYwSjFLckjX0ZoijDO2VNai7Z9ZZlxf+y37PFm+e8nIdz9DGPQql6mQARiQAAAAAAYOPrPoWOMocN049qqXKXLyZ2AZjJxaaPE4KcXGXDKHuqlCUoSTUotxknvTX/w+CwfaDoDpL3uqO1bLkuK4S9OP+CvjoaLlbDcjlMnHdE3FgAG4jgAAFh+z7T/TisJa+1FZ0t/ej8Pp8vInBRFF0q5RnBtSi1KLW9NFwas6ZjjKFNZKa7Nsfhl9GU2bj7Hvjwzoem5e+PblyuPoQ/2gaA6uXvVa7Mn3qX3ZfF5P5+ZCy9sTRGyEoTScZJxknxTKd1i0PLB3yrebi+1XL4o/XgScHI3LY+UQ+pYmyXcjw/ycs+ZMy2eU5FgVkVqfNkzTsnmfdthrykZ4N8I6sn3sgufvOIhwdSk/OMkl/wCbLWKx9jeDeeKxDWzs0wfN/al/6FnFBmtO5nSYa0qRkAEUkgAAAAAAAAAAAHxOCkmms09jXBoqTW/QTwd3ZXdTzlW/h5x9C3Tn6c0XDF0zqnx2xfGEuDJGNe6p6+CHm4yvhp5XBSgPfHYSdFk6rFlKLyf1/A8C/TTWqOWkmnowADJgHV1b0zLB3qxZuL7Nkfijzy5o5QPM4KUXFnuE3CSlHlF7Ye+NkIzg04ySlFrc0+Jy9aNCxxtDhsU49qqXKXLyZEvZ/rB1clhbX2ZPuW/uy+H1+fmWMUNkJUWfg6imyGVV7/PJQeJhKEpQmmpRbjJPemjRusLK9per3Si8ZVHallelxXCfpx8PIq2Ui7x7VbDcUV2PKqewxJn1gMHZiroUVR6U5vopfnm/BJZmvZMuL2aar+6U+8Wx761bE99VexqPg3vfojzk3qqGvnwS8bH3vQkmrmh4YHD14eG3ortS4zk9spfidMA59yberLxJJaIyADBkAAAAAAAAAAAAAAAiGvmr/X1+8VrvK12kt9kPqt/4lZF9lW686A92t66td1Y9y3Vz4rye9epaYOR/HL+ik6nifyx/v/pFgAWhSAAxJgyYcstq2NbV4Fs6lawrGU9Gb72vJWfzrhP6+JUFkz00PpizCXwvre2L7Sz2TjxiyNk4/dh6+Cfh3umfo+S/ZwUk00mmsmntTRR2vurzwF/ZT6mzOVT29nnB+XyLq0fjIX1V3VvOM4qUfU1NYtC147Dzot47YyyTlXNbpL9cWVOPc6Z+/jyX19Ktj7ufBVnsz1Y97u95tj3NT2JrZbZvS8lvfoXOami9H14WmuipZQguiub5t823t9TbPORc7Z6+D1TUq46GQAaDcAAAAAAAAAAAAAAAAAAYNXSOBhiKp1WLOMlk+a5Ncmt5tAJtPVGGk1oykdMaNnhbp0z3r7L4Tjwkv1wNItnXLQKxdPSgu9hm4fzrjF/reVNJZbHv3Mv8a9Ww9fJy2ZjOmzRcPgw2eU5GZyNa6wkmiMdD4uma8pGZSNeyZkk1w8st72Q492YW2pvPqrM4+EZrPL/uUn6k+IB7HtHyrwlt0ll10+x4xgss/wAXL8CfnO5WndlodFj69tagAGg3AAAAAAAAAAAAAAAAAAAAAAAAGCt/aJoDq5PF1LsyffJfdlwl5P5+ZZB5YrDxthKuaTjJOMk9zT3m2i11T3Ij5FCuhtZ+fbrDUlI7WtmhZ4HESqlm4PtVS+OP1W5nAsmdFCalFOPk59UtSal4PmyZ1tTtXp6RxMatqrj27pL7sOXm9y9eRx6KJ3WQrri5Sm1GKW+TZf2p+r0NH4aNSyc32rp/HN7/AEW5EXLyO1HRcssMWjfL38I7GFw8aoRrhFRjFKMUtyS2JI9gCiLhLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4OuGgI4/Dyr2KyOcqZfDLl5Pc/8ABQOMrlXOUJxcZRbjJPfFrevxP02RDWDUWjGYynFSaSX/ADEMv3+X2fLk/DInYmV29Yy4IeRj72pLk43sp1V6qCx10e3Nf8OmvsQf3/N8PDzLIPmMUkktmX5H0RbbXZJyZJrgoR0RkAGs9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/9k=",
        colorClass: ["border-blue-400", "dark:border-blue-600"],
        dates: [new Date("2021-08-01"), new Date("2022-05-01")],
        bullet_points: [
            "Training custom machine learning models to detect trash in rivers using Pytorch & Yolov5",
            "Parsing video streams with ffmpeg & Opencv and generating randomized datasets",
            "Managing concurrent image labeling",
            "Building internal DevOps CLI tools for GitLab project management"
        ]
    },
    {
        title: "Marketing Coordinator & Software Developer",
        company: "Neo Home Loans",
        colorClass: ["border-sky-400", "dark:border-sky-600"],
        image_url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAApVBMVEX///9DQ0RLyPI8PD1Ly/ZCOjhDNTBNxOxKmrWIiIhDQUFDPTtGU1lGgJZAQEFERUQ0NDVMuNs4ODkwMDHQ0NDw8PBJSUpOTk+vr6/5+fns7OxCNC7Ly8vBwcHk5ORTU1RiYmOkpKTY2NhJjKRIc4NGXGVLsNKAgIGPj5BtbW6ampupqapaWlt2dnZKob9Ie45GV15GZXFLs9ZETE9KnLlGZHBHbnyThrNaAAAHJklEQVR4nO2d61qjMBBAy621sCJCb7TQKq6trbau1/d/tAVplctAAoGS+M35ubuyHAkzkwCTXg9BEARBEARBEARBEARBEARBEARBEARBEARBEARBkN/KPPA8L5h3fRot4fqbiRUzHXpdn03juKOhbSmmFGMqlvIQdH1OTRI8TCxFSqNY04dl1yfWDMHt1Pm+eklMxXm6FV5y+biybEjvKGlbTzOBA894dlOm9y25nbldn2odxv6WrHeStPe+YJKut7Ep9WIUyx6Ouj5rekZDJRc6aSTNoRAZBMoMlIRpcrXjPLguizIDtaTtrB65lRw/PtHGlnJJ+2Y27lomz3hGHTppJK29z5Wk6++rhU4aSXvj8ZJBvI1pNasXo1gSDxlkNDTrhk4yYXCddDsHCXYTttBJI+msuirPw8xgtax3lIwyyNnL8zlNUd2kZFienzG4hkW1c0a9k6RzpvLc9fbK2fWOkpayaX2Bxxu2kxloaTmDBLsWMwMtYQa52rWSQZa71XlCJ5kw7qxumw6uwbbtxFeNKO40mSXdocOTXoziPDQmuDQ7v/tA7GlDQ3XUUXIgY5qNhJyAwxF6wlQauBnHEr+CoeKUvczZ8nkPnlA2rIK+U/4/GFdJdI35lDUpeUDJIP17h7XEWZWPUe0gD5JcLnQmPz1zQPmZpGjesAl6hEvYH8gp1DX5t16C9jFQ08d7J44Khy2e7glhJmsoq4OPfl0/fXGpZg93QTRUmBL/mBRmcobhSd31641U42qdFaQxNCcshiOruqGsvr7VCTj9z0FOkMZQslhy4syuYSir8t/Kl1HXLvJ+lIY+g+FDjVH6dWIHo1rA0f5cQ4JUhvZtB4ZhwLmvMFL1fi7EVDBkCjXDuoaVAo4hHQoE6QyH3RiGqXFCN1JzSVAUw3CkflKkRl27K/Tj3fDr/EgjVXvLJ0GBDGX1+l/5Gfb/qmWCvBmCJ1tWi4d1NpDkk4fhy1C9hEaceiisxbV7IAmqF8nIypnhm9EHokZYi4NnCSbBKDppl9wa/tGlPhT5wdRoTKALvr4yJINrQ8kwoFsrX4vDdfZl9Kvg3DAcfM9yfhKUqcX1PlBnq9dxpce7YVRFv0IBx/hR1P5BIeb9mDz5N4RnQj+pUV88A38dXuXjMQUwLL3LJEMn3KlCGIIrEnGkBOvsVLQVw7A428EZM1miC2JYVLFAF/Cgp6oeYQwl3XgvraqPP6U+Z+oBcQyjmUM+NWYF87MPkQzD2R+QGlOCwAxSKMMw4JTO4GVoFUAsQwmuxY8/sH6DJlaiGcK1+Bd38ORYOMOoFodm/+rdAj6meIYFK9rqoWCZSkRDUi3+CwyjWhxIjSq4TCWWof79RwWrFsAylUiGuvb5kw/A1KgOXnIZUSBD422dWtnX7uFnoNkfE8YwngarFz+FtU6a/AplqGvHmUUqZC6AWjw7uxDEMLXYlAiZYC2efmQshGFmhp9c2S8IOIlHxiIY5h7qhiHz5yL1X8pXagQwhBRSy1Q6mBpPj4y5NwQf6qqD5E+Btfh3YuHdsCCU6OlMAq96x6mRc0NoaUaVs4tNpbU414bfSTB93n+g04SXqcLEwrPhAi7LCp5zw+viB2nBraG8vshfE1XOl9YnCmLSXfK3xpchsFZR8hQ/Aq7FUwOAK0PgCl4SXv0qXqYSwpD4No1U8MhYFEP1wii/gDHgI2MRDBMPdQkUvDzLu6G6rvAqNFiLc25Y8XV2Qyp4f49Xw6LXoIoBPkTg2TD7UJcKMDXyaQjV2TSAj4x5NKRJgkUHy9firRtWf1ef4rXgYvJzy9bf1ScaLtI3D92r3cVEtXj6gOQvu9i+tyB+M6PdXSc5UL6eX3LAj9fUEV/II4Lpmxnid0+SoaVg+/owQq98QKbvnojfrnEA27drvS3PnznHMIXSXs8jDtPOYfyGtDfl/SKyfgfc83m/iA5zT55f/z1+GE55HqfmpIHWUQHhg/UuMe1GmtR4nXaGKsNUGmqnFCh83ov2pLE2Q+6Gww4upsOW6jOMbnhpgxUTNeFruuFXsKvdH7hpTMWattMt0muzkyc1UcfP9prSud7e7rjnnrJpu2vr2N823VGXlvP1bp/PbjrpfXnWBp/z29I9D5rXs58ez94cOthJ5+k0aCpOS6GTQrJ+h3lqwszQTqtLWrxNnV0C6PVMDhpeRxmklVtSiZqWd213pNGW8zFfmYGrxvMNbRtw0rO43DxgedtIl1q+d9dhbtLeZWagZTSsn0GiXa5E2IjF9TaOXWefGYeDzEBL5Q0vTFvZsDxC6gKq7axOetaNaPs9xcxnFBmE18xAS5hByoJrtLkcv1sD0VJYnkfLLbxv70QLtFWLYklCZAZaXH9j2ck9LPkpqpvDne2l4z6kE+EyAy3ucuT7/mgpZGZAEARBEARBEARBEARBEARBEARBEARBEARBEARBEISG/95VyTWQvzTiAAAAAElFTkSuQmCC",
        dates: [new Date("2021-01-01"), new Date("2021-08-01")],
        bullet_points: [
            "Graphic designing for marketing and promotional materials",
            "Created PowerBI & Domo dashboards for data analytics",
            "Built API middleware and Selenium programs",
            "Deployed Docker containers to Microsoft Azure",
            "Filmed and edited promotional material",
            "Built and deployed React web app on Azure"
        ]
    },
    {
        title: "Data Analyst & Admin Assistant",
        company: "Fairway Independent Mortgage Corporation",
        image_url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAzFBMVEUMlkj///8AlEVQrWn///4HmUsLl0cAkju02cEAlUNSsHgAkDsAlDv//f/8//+t2LxYr3k4qmmm1LcAjjD///sNlUoAkDYAkT8KmEUAjTUAji8AjDIVnlEAkEAAjy35/vtLsnbM59dDqG71/Pdft4Vsu47f8ecAiiWBwZWOyaRvt4YupF/t+vLH6NIAlzmbz7CSy6heuYLG5dXY7t/v/vV4xZQmolQcnFep07aUx6O02cWBwZY0qmVFq3We0rB3vpYAggYAewCLw5g6rGFWRTCJAAAOoElEQVR4nO2dDVfiOBeAm25JiIUilLQpIBVBlK9BZdQdnXF25/3//+m9aVWQJkhrC+2e3jPu7nG6tE9vcr9yEzTtvy36X8d+gqylJCy+lITFl5Kw+FISFl9KwuJLSVh8KQmLLyVh8aUkLL6UhMWXkrD4UhIWX0rC4ktJWHwpCYsvRyDE+KC3OzQh1thhb3h4HdKaSw96wwMTUqd3PZkS54C3PBwh5prmzFZISKPmYg0fZrweUIeMOkuE/LYFiP60Sw9kcQ5FCDT2+RwZbcCz6gC5qLj8IFo8ECHG7rcqQoYBP+Kf8G907dDKAW59AEIsXIR96aNtWc0chlnWY/UQOsSa2xug+jYgDNWlrWc+GQ9BSOyJMC4RHcJonf/yeMZ3PwCh0xyjYP5tiR/8rlpzs719hoScMYyx3mkh1I7obz1S/ZFNNc55VnY1Q0Lwd1zrnwwFxg6po0GFMC0zi5PlKAULQ55eNaXksyz42+c+zSwiz1KHun0vzItyiG5YnPGsk9VjZEbINbO3+oxtQ1oe1SpZ6DErQkz7E4n93CHzczOTtCojQm6Ci6hbu23MhrTFXK3SWgaPkg2hW2uB/vbmexP/0tZTf5a0CTmEKLQ7Gip1BT+GoRy9i0dHxLFpeo60CcHLE3oXDULfBegsNSFCky7MxjQtTsqEDCzMJWBYlpwxDE4NpQMB9PHMSTVUTZvQeVwBn1pFaLD80VKN4YDRQi8mSfGRUiSE2aPbN8pHt0SAtprZJiHdqQ+jtY3q0ldhofmJrWGe0mxMU4fYac4VBlQMWhiB91cc5hhEc7WqOpYz4NonTsR1aUiKhMRtiMdWzDHguYPHDvINTHX7ZK7Wdlu8DFtcmMJjpUaod2+/v5LI+axbm2LMOQ6zKmq/KEJWwLPgZ8XNVLSYDiHWCFuodYLqBmo52zGZPRuLEal2LBOPpmBVUyBkFbAwz2oXJxz8+MKMPCyD/ytUl0rGTQ9/WY8pEHJOHsc7kkBQ0sSW1H8hQa5VFmodiiHcMulXvX8KhK4DLsJXDzY06JmaLrEakPXSjjLACyqryB91vhiqfoVQlCmw1hWlbPkjglGEGO1yRzkNa1Q4DkNlg+uiOG5yXsGJ6+NfIoQf02kghedGwchdUMp324uw2t+We39IwNq/u5QxLanR+QKh8Ff2rY/g4ZRDdHhqc6HoXR/DqL0Ea6uyOMC4erSTG9UvzUPC78QIq8tHKQw7cBGB21YiwuATf+88qAoe7XDw3ji1g49ShsHYK+2nBXMQjP3eK6G6dx9aFpWMmzYY7SSeIyEhDBrSG6stvUgvJnaMogQ38SKISOXii/HgJvKNSXVIzZdd77wOLuIMa3uvnsFYpd1RdGnj/Y3Bnb6PuklKVQkJhf2zdgwq61LUP/d/5ViULlzSUBIGfxY8wRpHAkLMaq46+QlKFNUaSTSivOY4HAEqubd18TbiWJ0EhNSBOET1EAZkPpDAJo1DiHkTfobi9aHVg8vixaoJCLvVwElJpQ3GAlxE8qVdiHF3VcrhxZ5SLZb3j09oTkQ+oEgJfLF0LdacEiav4A/0/m+1xRHB3QPG2RIS1d0D0/rsfbmmy0TGsSOnuuvGGiAxCblG75Xv1wAXQdKoBOr26TBI9eU3IrHCm5iEVCN/K1+uPxUW5svVXFGsqjlBzUeO2NQzHKWYOS0VYIO6OI3eSiamGXdCxyEljOX44xJiM0JYD172/Lwb65M+FSo6OIy2JG/MVocSwuARXrw069ThvcjjQLoE2YzVhJMCIQq6mxLF/TsFJnT/0pfq8OCENx09no/a717w43KJ/z88YcuO9RmxRO9Hy3gHJxw66evvTahGL45PuIwWe1MTzrR+pJR3cMKpnl0nLKQRThVtVakOTniabT+z2dh2GSXhRykJt6QkjCNMBPKYi2z5tWgsquh6KK9XQKREGtu9G4Uh5BgzyJSY7po1x/E8h/BKpRdIhXPidO1O/8x17ca2Q8yY0I3kh4l1iCkxPVJpTn+0nu7Gwy2/7s/Hi6eXyf3F0/YNsyaM1DSTEOq66fV7o+XT6r0mI+aaPONtH3QeaqSamLAiQhTMdUpsfLK826exz5D1wOWWEGuMY+p6ZPS3Mn3fFOUbyC0h2E1i934EPRvt7Uhsl2zrMbeExOndCOUZ7fcn3rH4L8Qa+kP4s10+zbaKkYBQOD1NN+mzqphtGci33pdZ/fFT62Z62nzklIAXAanVSG92cfs8aT2NRSfVRaxc5hCEkKr3m4EJVhezA9JV4/mi0rE9k7pUf+/5YoxpOkQC1BRekz7cPmRaa0sySr85l2J0qtZbgt/Pq88zx+4QKlrCOMfBcpuucdMkxPO8bte2baFPYppn8XxT9oQmmQxh7lmyrU+hGIvnB888o+GqmfgsRl3i2E7l5+h5+ffTYrAaB7K6qzaWf0aVWAsHGRIGWnDMpdTqt8GaBi0cw6dziNrEM4d6w7pLuvbs8qU6Vo3pE5obW4pd80aut3pYsbeqJ7bzqrsg7qam17tshO7SUPUa54ew5lwPFR4hePbVM3V0xt+W4uiZV7luzDevkL+evBDq9q/A+4lHlVFWm2AzgzMWRDewbtqzl8CdCG8p/lg5JsSswrDJIzlBoJrw2a0X7IRzT1yuE2+2/NAzHMYERth+sh3THJ1QlL/17qUVNKVFCOuC8eabid8u1nSHi2DgA4X1OkyHq8afu/zpkFNaGcgj5+B3y5pY4wysC8O1zqzxrrS1DpFwkfePxCP9xvYnHZ+QOtOApR1dVIEnb2Cii17vIPSi9u2b+j4i3v3p2cSFeYqdxjb+cQnhvyhRtHyLFqPBzAn9tfANZ/ZoK48K88HBdc0jb249Wok6KiHD2remoqMWfunfOmFXE64wpndHcxQdzP6y199sfcoZIa50fssVKKRBCHtbAOCdCxifvr/u1gtQx79twj90bOaMULNFT7O8o3YoWqXe9hc4vbehvPn046ldY7zCNvsBckQISQEhkhzQCtOHp2+vSQ+4eBrZHyUcy/CyI8mLckSINfo4lPR811Ed0tvbjWVUO7I/SiDceET25Dki1M5mvmhJj+rQQque+f5U1G5J9ketHk35LXNESC6EO4jOwaDfm63n1WyM6sZ2c+qz2AEkXUvOCSHDvHYii5QDkvug1Uak7xq3r7cvEftGH86UHZU5IaSMnMsAxS4K/+I9COX6WeR/h3ladZm6ozIfhBo2L6ReAh5tXnFfz0qAIKY3386kwIj+trGm7orNA6EOOpwFwbNkZ8/KfTNEmJ+dI4miT0DFO7o58kAIRr7iS1IJcVDCwg59Ja1g5n1s3AzKGMj/+Ul3eg4IT2ASzlFbYkPbqNEPu11Fkak72bpAuE7r0+JnDghP9f4AWZKdWW3U6rBwW5c4b6+13TptWfVh79Pqbh4IOy1kSfY+Wajlaa+ZLtY6je1ZKszsI/20Kz0HhBcnEe3BAIScodEN5yCku+xK5iXQbI/6fA4IT32pp4c5+L4piHYipQixiPFrn41ROSCcS9YCfQRW9HVXJGR7zousavPb2edJc0BoWNHidBsNuvh1ijHNnsh2ge3ZtJkDwgid2A86XuuHkcvINXUDrfY8+yqHhGKMDjeCFIhYo/PUMNieK0i5JBQbBt6zJb0nmYIGut13o10eCS10W1ufoSs6YKOMVW/fp8whoYFuNvb/etHiKaQT/v4bl3NIiAYbRtKJFhfF4wol73nLHBIOydrM0Kb0kkWX770/KoeEP+laP57knB3wJTO6/+k6+SO8fquZYc5kwRo8bkNRVpNK7ggH3fW1dCTf8B2rmSJnhIa1sf9JJ0MkK09V+3FumTNCNFoPQLHyZ8kWSnuxdoHliVBsxO+8XadhuR31wdnH2sdLIl3QxyNso++UszdPgT1ZFyk8a9ONRWhGmpKPRmgZaFRbr/u5E/mu/ZXNY50YED1K4ojz8K4jXERwHda+WbKzStromcbbK+xJintHImyjtQXhzJGe4gGJcKxv74Axbw/zMw8nG9+vQnuKi57ieHuNYxqtcx2NcO68WxmNm/J+jDY8Xpz7MWpG476jEZ5stF/jmeKESMuJE8/opDJGkdNej0JobIRrokvUvlN03TVqnPPavvKwlO3lPo4ODfSgv1+D9ZlCz7GPh5YdonIUQgtV7fU12FEeThJ8D8u+YskP4zkKYXszX8CBIVUdZLr3Meb1sEUxL6P0Zd0pgjW5L0xNgFDEfTo1bcc7o5jtjCDSItyou2CdZwoY6hBzZzoY+uOXyieHbqVE+ELWdRdsbi+Fpk/Imc7GaF4VTe+37s6aTyqEFtpsbWPOMM53IiQi1Fj/Oxr9c3X1zy8fnbrZj9LWZihWu/1sx9bXCRlZotPeYLBq9WfIJ7vipFTWnlBvM1DpDGJ9r0UiQo1AhPGAqhO0vKqi37vOxkmDELL2zU+sxPvmjkSEvIl+mA/o8l+08M7R0658JQXCOpptqtBcfrJFLQ3Csymakke0WsEkfECDXflKEsLts5s2VwKxZqsPW09JmjrWL9Af5xE1Vqsr9j+0SFGH4Ar+RE4Zu9XXp3hyep4k+owlBGNMYHg+oOcRmnZakJimRyj2Km+fjDzsb7gjvt/6YnKxhMaCEsLPynh6NWg4BtqZcsYnJNvfAfRirjNfzPoZT0KEeiJko9y3ZlcOvaqN0XWahEK6L+u7iYO4P9R3a5LmmhTFQP6FGJJwy94c3f3584TQxNl5AlCSM2jN08HGMF3ZG7Uz7GY7SIcvlUBhIsuu3QibtmimG5cKYZja4pCOV+GbJ6YyXMlSdNN9L5Vg6jo17Jn6J19mkuSUXfGJuq6JM1ao9vF7NsTt9ewEv71MFuyGFhsgIAhPnbBgUhIWX0rC4ktJWHwpCYsvJWHxpSQsvpSExZeSsPhSEhZfSsLiS0lYfCkJiy8lYfGlJCy+lITFl5Kw+FISFl9KwuJLSVh8KQmLLyVh8aUkLL6UhMWXkrD4UhIWX4Aww77sXMhf2l//cZn+HyKRFgECzwLGAAAAAElFTkSuQmCC",       
        colorClass: ["border-emerald-400", "dark:border-emerald-600"],
        dates: [new Date("2020-06-01"), new Date("2021-01-01")],
        bullet_points: [
            "Automated CRM data transfer and form-filling using Python (Selenium package)",
            "Automated creation of gifting order spreadsheets using Python (exchangelib and pandas packages)",
            "Built dashboards in PowerBI analyzing loan operations volume and performance",
            "Built reports through Encompass LOS",
            "Assisted in new technology adoption and IT needs"
        ]
    },
    {
        title: "Software Engineer (Contract)",
        company: "University of Utah - Genetics Lab",
        colorClass: ["border-rose-400", "dark:border-rose-600"],
        image_url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOsAAADXCAMAAADMbFYxAAAAY1BMVEXMAAD////JAADz1dXuwMDxy8vROzvZaGjjlJT55+frtLTHAADVTk7aa2vSPj7y0tL++fnYYWHPKCjQLS3RNjbTRETUSUnVUlLXWlrcc3P67u7ijY3NFxf23d389PTOHh7deXkzXNt8AAACzElEQVR4nO3d3VJaQRBFYXoMEhUUEAWNJnn/p4yxcsf56Zmme2bi2tfWWf0V3ljWKRbydbaofUDgPqw3VzF7GOpvH4Lir5/WH3cpZHdD1puo+O2n9XtahCwNWqPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yX8g68u5gTPyf9Xa3OttmbXry2+b8kavTkPX1NPCTGyPseP7I3XL8Xd+l6cO+H3mqdrbftDT4pu249Zspd13XusSKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsXarvXwfmXZu4kabF0k27qyVh1WrFj7GVasWPsZVqxY+xlWrFj7GVasf/fzrfbF5dtv86yy/VX75NLtx0ij1m6xj6OicWun2HHqlLVL7AR10irbfe3Tc3eY4kxaRTrDTlLnrF19smmaOmcVeawtUG+OOm/tBptm/xE6b+0Em+a/n0hhlUNth2IKqsraATY9KRgqqxwa/6tHRVVa5bpprI6qtTaNTc86g9Yq981itVS9tVlsWmsFeqs8NYnVU3OsTWIzqFnWBrHpmHF+llWeG8NmUTOtjWHzqLlWWTeETYPfsno5a0PYXGq+VY6NYLOpBdZGsGmXfXiBtQlsAbXI2gC2hFpmlVNlbBG10FoZm1ZFRxdaq2ILqcVW2VXDpk3hycXWathiqsFaCZteig82WGVVAWugmqwVsBaqzRqONVGNVtmEYm1UqzUUm37bbrVa5SUMa6XarWFYM/UC1g9syMzUS1i7Gdb/c38AbI1hoyuPVwIAAAAASUVORK5CYII=",
        dates: [new Date("2020-05-01"), new Date("2020-07-01")],
        bullet_points: [
            "Worked as a software developer for a genetics research lab",
            "Wrote backend software in Python using the Flask framework with connections to an SQLite DB",
            "Significantly reduced false conflicts in the Clinvar Miner genetics database",
            "Worked with Linux server hosting",
            "Efficiently found closest common condition from sets of conditions from the Mondo Disease Ontology"
        ]
    },
    {
        title: "Data Visualization Intern",
        company: "BrainStorm Inc.",
        colorClass: ["border-yellow-400", "dark:border-yellow-600"],
        image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ892BvOyWHhb4dDGu2-CzIRwmuO6TJf4SP4B60gyGLX2iMEnGXuso5kCxE48VEf8Hal5k&usqp=CAU",
        dates: [new Date("2020-05-01"), new Date("2020-06-30")],
        bullet_points: [
            "Developed data dashboards using PowerBI and PowerApps",
            "Integrated Microsoft semantic analysis on data using Python and PowerBI",
            "Worked with databases and data services like Snowflake",
            "UI/UX dashboard design experience",
            "Created screen capture videos for training purposes"
        ]
    },
    {
        title: "Software Development Intern",
        company: "Red Pepper Software",
        colorClass: ["border-red-400", "dark:border-red-600"],
        image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThIJV8WvvqHPlpiG0osF8OqszhQyF83Z3uerK7zKTSxwOGvYvjdYHWxi5G_b0COkmnp4g&usqp=CAU",
        dates: [new Date("2019-03-01"), new Date("2019-08-01")],
        bullet_points: [
            "Full stack web development experience with SQL databases, C# .NET Core backend, and REACT and Vue frontend frameworks",
            "Maintained various projects for multiple clients",
            "Created unit tests for new features",
            "Built and redesigned features",
            "Fixed bugs",
            "Worked using the AGILE framework using Jira",
            "Worked with REST APIs"
        ]
    }
];

// src/routes/work/+page.svelte
<script lang="ts">
	import type { WorkEntry } from "$lib/types";
	import EntryComp from "../../components/WorkEntry.svelte";
	const workEntries: WorkEntry[] = [
		{
			title: "Software Development Intern",
			company: "Lucid Software - Data Infrastructure Team",
			image_url:
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAkFBMVEUoLTP///8oLTEoLDVHTFImLTP///0pLDEpLDPZ3eApLjJaXmErMDYkKS8nKi/8/PxXWFwsMDne3+P6+/8hJiwwMzgkKDE3OD0jKCxbXmOJio4vNDopKi66u7+YnJ8oLC3y8/dwcXPS09esrbFpam9RUlZCQ0fm5+l/gISytbqUl5x2d3vIyMo4O0Dz9fTu7fKdv4/FAAAGM0lEQVR4nO2ci3baOBBAZRszAkYyfsiY2EnzImkb0v7/363kBykJSbeLKaPsXHIO52ACuhmNZEcji4n4JLAINViEGixCDRahBotQg0WowSLUYBFqsAg1WIQaLEINFqEGi1CDRajBItRgEWqwCDVYhBosQg0WoQaLUINFqMEi1DitSHTST99jbJHQ4p6jMk3juExBA0ipRGSdpAQY+eteOJlIWlqVKAJjCokKvRVRtvFpGSFUzXoi0d+ICBSIIi3g4S5fS6W8E4kt7hkr0IWWq4ufQbCBGruj/omE2hhAc58FeZ7cQ9Ef9U4kDG1uwOYyCBL7s64QR/6at5xExObJfP5wlQd54H42iGrkr3nLaCIKa6Fcjqu6Ck3VXDwGiQ2HYzEMAKdkLBH7Ry+EzWllPeZheJPlXbdyImufRIaIaKPnZnKZ23BYien0RWQYz07EaCIo3NCEEIYrmxwdySACHok4FeEi8vXRJng+nVqLFpcjEMY9433dK8bLkTbRYX3rYpAHbSiCaRuTxRePRATaXC8m3/I2w9scb/uVbyISbZab79cuO5xHMu3TpOtaoQciNhKIRdM08JQFQ5bv041a0Wmvso4VUXbyKKSBZrkNkoMaw4RIXMQmeGF0Y0/Wg3w3lfsoIkRdF88X13nXq6YeiwhltkF3PuJ1ROyVINwG+XWXIQdNvBBRtRKmP0MMgh8eR8SeLcIsaYNhe5a/OeKaB7ODgfBOJAw/lch0erBb+SMiOpEpi4zESCJTFhmL40Xmn0NEdCIfwiJ/AovsYJFxYZEdLDIuLLKDRcaFRXawyLiwyI7/qYhsAQh79hd/jpBlkf8o8kInYl8ep8udWUR8ApGRYZEdfybyskwdOYTNe5ByBM1zi4DfIq5sBZWopcTnq6Us0s5KHFEO9bdFlLVoZ47aPoraPD262s3SP5G+5nGuAbSB5TYPkiVg5KcI1vMQtQ4nd+3hZQEeinQ1g6Cb5vn7z8DVEuVLAx52rdZljvPmxv2SqxZ0EUlT70TSSKAuVpttt549nQb5wkak9EWkmzbsu9Gd+U7ukqCtMWgXVZYakHJEprvFn0Uo3FaSskwlNKYxF497b1zaKfHoVvwVkbW96kjTMq0L2TTVTRbs16wsR6mYP2XX+lWkjKMykiVstknyqq7LIxGwXSuNUFbPV9dv30ZfZFBxNY2oFJqvP/sSVM8iMogsGgjtXL647evlE/9EOhZfYF49XPYlqImPEdmJGJcc+VDavF9n54NI1+x7czPMHIeKCmiLJLvnJLjYDq8erI6gKfLSVJcLLi2urx6TrkT7nTIP2iI/+tEp/zZphlJzz0SGxrYT+Pa+Cud+i7hwPD6t7NEwy19LeiIyqFytvjRhuNLeRqRr7eXEnrKDRg1ZP4a9U9JFRQSg+eXE3LXV9arb+wZQSemqUGcfWDiR+W6jDBWRpKvIDvLrixVILCN34SfC7P1uRU8k2WkkeX63qgBQRPZqKook/HuRs17q9hEJgmGX2OWmAQDtbo9gQyI8E+lH2DyY3ZhGm0LWNWKs2t34vxNxyT7suj67SJcbLjlKkLJwO5YK1zjr8dscISLSDb+5tQjyuwcsIhG5zZWIdaxUDL3n70XcZ51ZpN12YT2267mWkUtwZVViFdvO5dY/2oBRF1G1Cs3MZcjsyWgD3fpNFA0LOqBBZ+9sWRpEBKpuqeGYWykcvX1PKdRuj9X3Zzvk2oDsi4gKUGcfWNg/wRLbZZMzixRxrXSWf3swGlxqDCLDcRNqczmbzbIsmx0iy243KNw/sY+83cixIjaja7xbI4Lbsy7Ua5EqRI0GVmY+gL8+UJtnrdD9E/vMIgqLwlQrrbVAEafp6+O269Wqlhp2VRti72GgkALL80ckxhorA5Vrgu3ob+624fo+ugqUQeMVbk0XVRfD84oUNk9sc7BSmMZx2peYhF3xjBRuCLYNdcu4B09BZHtfofT8XStN7dgp7BgLtY1Iql6L2BdrJdKym7sPiKDrWOn5I0IGFqEGi1CDRajBItRgEWqwCDVYhBosQg0WoQaLUINFqMEi1GARarAINViEGixCDRahBotQg0WowSLUYBFqsAg1WIQaLEINFqEGi1CDRajxWUT+AZd4aHmhwyNEAAAAAElFTkSuQmCC",
			dates: [new Date("2023-05-15"), new Date("2023-08-15")],
			colorClass: ["border-blue-400", "dark:border-blue-600"],
			bullet_points: [
				"Designed and built a new dashboard for monitoring user events & metrics, including tree-based action tracking.",
				"Implemented flow-based math operation shapes in LucidSpark during a hackathon.",
				"Fixed bugs and added features to internal data infrastructure & reporting tools.",
			],
		},
		{
			title: "Software Development Intern",
			company: "InfluxData - Edge Team",
			image_url:
				"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIHEBMQEBAVEREREBEWFhYVEBYQFRISGBUZFxgXGRkYKDQhGx4mHhYWLT0hMSkrLi4wGCs1Oj8tNzQuLywBCgoKDg0OGBAQGy8gHSAwNy0tLTctLSstLjcrLS0tLSstNzctKy0tLS0uLS0tLS0tLS0tLy0tKy8rLS0tLS0tLf/AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAwADAQEAAAAAAAAAAAAABQYHAwQIAgH/xABEEAABAwIDAwgFCgQFBQAAAAABAAIDBBEFBhIhQVEHEyIxYXGRoUJScoGSFBUjMmKCorHB0bLC4fAzU5PS8SUmQ2OE/8QAGgEBAAMBAQEAAAAAAAAAAAAAAAECBAMFBv/EACwRAAIBAwMBBgYDAAAAAAAAAAABAgMEERIhMVEFEyIyQWEUM3GBkbFSofD/2gAMAwEAAhEDEQA/ALqiIvSPiQiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIuCtrY6Bhkme2Ng6y42CEpN7I50XWw7EYsTZzkEjZGXtdpvY8DwXK2oY5xjD2l7QLtDhqHeFJLi08M5ERFBUIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIijMwY5FgMJllPENaD0nu4D91JaMXJ4XJy4zi0WCxOmndpaOr1nO3NaN5WI5rzPLmSTU/oRNPQjB2N7Txd2rgzJmGbMMvOSnoi+hgPRY3gO3q2qJXSMcHv2lmqS1S836JrKuYpMuzCRm1jrCRl9j2/uNxWk5lwaLONO2sonfTtb0SDpL7bSx/Bw3fsscViyZmh+XJb7XQPI5xl/wATb+kPNGvUvcUG33lPzL+zloc6Yhg7ix0rn6TYsmGsgjcSekPFWzC+VSN9hU05Z9qM6h8LrW8SuznPLUeZ4RW0dnSlt+j/AOZvVbb6Yt+iyR7SwkEEEGxBFiCmEznCnQuI5aw/U9A4XmejxW3NVDC4+i46HX9l1iVLrzMpfC80VmFWEVQ8NHok62fC64UOHQz1Oy/4P8noJFluF8qj2WFTTtePWjOg/Cb38QrfheeKHEtgnEbvVlHN+f1fNVaaMNSzrQ5RY0QbUVTKEREAREQBERAEREAREQBEVezdmuLLjNvTncOhHf8AE7g387KeS9OnKctMVudjM+ZIcuxa5DqeR0Iwek8/oOJWH45jM2OSmWZ1yeoeixvqtG4LixXEpcWldNM8ue4+4DgBuC6i6Rjg+htbSNFZ5YREVzWEREBasjZtdl6TRJd1NIekN7D67fDaN6tuecnjHGitobOe9oLmtIAmb1h7ftdm/v68tpaZ9W9scbS97yA1oFySt7yhhT8Fo4oJHXe3UTY3DS5xOkd11zlseZeNUZKpB4l+zFocr1sztIpJr9sTmDxNgFPUHJnW1G2Qxwjfqfqd4MuPNW7Pedn5ekbBDG1zywOLn3IAJIAAFtuxZ9X54r67rqHMHCMCK3vbt81KbZ0hUuKsU0kky4wcmlLQjXV1Zt9yBvi691yc/gWB/VDJXjgHVNz3uu1ZZPUPqDqe9z3He5xcfErjTT1L/Czl55t/TY1Os5VYmG0NK5w4vkEfk0FXbAMWZjlOyojBAfe7T1tcDYjYvOy1jkdrecgmgPXHIHjueLfmzzUSikjJeWdOFLVBcGgoiLmeOEREAREQBERAEREJKtnXODMut0Ms+ocNjdzB6zv23rFq+skxCR0sry97zck7Sf72Ls5gppqSpkbU357WS4nbqub6geBuo9dorB9Ja28KUMrdv1CIisagiIgC7GH0MmJSNihYXvebAD+vUO1cuD4VLjErYYG6nnwaN7nHcFqsUdJyc0t3ESVMje58juA9Vg/vaqtmevX0eGO8nwj8w7DaXk+pufnIfUuba+9zvUj7OJ/4VJjzpUVdfFUSSFsbZWjQ1xDGxE9IW37N5UJjeMzY3KZp3XJ6h6LG+q0bgo8KFHqUp22zlU3k/wDbGkcslFZ9POB9Zr4z7jqb/E7wWbrWc2n57wOKfrcxsMh9ofRv8yfBZMpiRZSfd6Xym0ERFY2BXXkmrfk9dzZ6pont+83pjya7xVKUjlyt+b6uCa9gyVhPs36XldQ+DlXhrpyj7HohERcD5YIiIQEREAREQBERCSmYvh9Pn+m5yE6J4iQNQs5jt8cgG4/3vWQV1I+gkdFK0skYbEHrBVqxLEZcoYtO+L6plLnM6mvjf09PnsO5W/HsHgz3TNqqUgTtbYbiTvifwPA/oV0W30PcpTdDGfI+PYx9F9zwup3OY9pa5pIcCLEEbLG6+F0PSCksAwObHpRFC2+9zj9VjeLiufLGXZcxTc3GLNG17yOixv6nrsFo2LYrS5ApxT0zQ+ocL2Jub/5kh/Ifkqt+iMtau4vRDeTPqoqaTk5pubZ9JUyC9vSkd6zvVYNw/qVlOK4lLi0rppnFz3H3AcANwXxX1smISOlleXvebkneuuiRahQVPxPeT5YREVjQazyfH53wmelPW3nmDsD23afiJ8Fk7hpJB3K/8jtbzVRNCTskiDh7TD+z3Kr5xovm+uqI7WAlc4Dg1/THk4Ki5Zio+GvOHXch0RFc2hAiID0Plut+caOCW9y+Fl/aAs7zBUkqVyTVnyihMZO2GVwt9l3SHmXK6rg+T5a4hoqSj7hERQcQiIgCIiAIiIDJeWCi5qpimAsJYtJ7XMP7Oaq5lLMkmXJtbbujdYSMvsc3j7Q3FaNyt0XP0TZQNsMzbng1w0nz0rHV1juj6Gzaq26jL6Gt5sy9Fm+nFbREGbTfZs50D0XcHj+nBUvL2SqnFZtEkb4Y2npvewtsODQesrvcleLSUtYKcEmKcPu3cHNYXBw+G3/C2Qmyq21sZatepbZpLdehQsx5hgyVCKOia3nre0Gbtb+Lzw/SwWT1NQ+re6SRxe9xuSTck+9aFj3JnO975IJxNqc51pOi/ab/AFtoce3YqZimX6rCv8eB7B62nUz4m7FaODXaOil4XlvnqRiIiubQiIgJ3I1b8gxCnfuMmg9z+h/N5Kf5X6LmauOYDZLFbvcw2PkWqixvMbg4GxBBHYVqvKYwYphtPVNHUY3dzJWbfPSqPlGKt4K8JddjKERFc2hERAaByO1vNVE0N9kkQcPaYf2e5aysDyNW/IMQp37jJoPc/ofzeS3xcp8ng9pQxV1dQiIqHnBERAEREAREQEXmmj+X0VRFa5dC8j2mjU3zAXnpemV50x6i+bqqaHdHK9o9m/R8rLpA9jsue0o/cuHJDhvP1MlQRshjs3237P4Q7xULn7F3YnXS2cSyJ2hgvsGnYSO9wJ96vWUgMuYM+pdse9skvvPQjHv6Pisic7USTtJ81K3eTTRXeVpz6bIncLzjW4XYMqHOaPRf9K3u6XV7lb8L5VL2bVU/e6I/yu/3LMkUuKO07WlPlGv3wXNH+WyR3/zPufAOPio3E+SsG7qWo7myN3e23/asyUlhmP1OFf4E72D1dV2/CdhUaWjj8NUh8uf2e53MUydW4Xcvp3OaPSZ9I3v6PV71AkEdYWgYXypTw2FRCyUcWnmnfqPIKeGYsIzLsqGNY87PpWaHf6jerxTLXJPf1oeeGfdGQrWcB/65gEkR2ujjlb95h5xn8vguOt5NKWvGukqC0Hq2idnuI2+ZU5kTLUuXIpY5pGPEjwQGXIAtbbqA6+HYobTRwubmnOCae6aZhxRXat5NqxszmxBjotR0vMgA032XHXf3KToOSlx2z1IHZGwu/E635K2pGt3lFLOozZfrWlxsBcngtfGUMJwTbUPBI2/TTgE/dba/gvoZxwvCTppY9TuoCCDSSeq1za/mo1HL43Py4Nme4JlOtr5GaIHxjUDre0xtbt+td3X7lvK4aKZ1RG174zE5wuWOILm9htvXMqN5PJurmVZrKxgIiKpkCIiAIiIAiIgCx/lFwcy4qxrBtqxFbhqJ5s/wg+9bAo2twaOsqYKl31qcSWFtjtQtt7lZPBpta/dTz7Mp/KrVtw+jgo49geRs/wDVELAH3lvgsoVr5TMS+cK97QbtgaIh3ja78RI9yqi6RWEe7aQ00lnl7hERWNIREQBERAdmir5aB2qGV8Z4teW/ktd5M8fnxuGUVB1mJzAH2ALg4HYbcNPmsZWuYB/2zgbpzsfIx0g9uToR+WgqkjBfwi4JY3bwiLzPykSxyviow1rGOLeccNbnEbwDsA8VTq/NFZX35yqkIO4O0N+FtgogrlpKV9Y9scbC97zYAC5JU4SNFO3pU1sj5ijdUODWguc42AG0uJ2blsGRcjtwcNqKgB1QRcN62w/u7t3buK7OSsmMwFollAfUkbT1tiv6Le3tVtVJS9EeXeXurwU+AiIqHlhERAEREAREQBERAEREJMFzRl6qw6aV0sbnNMj3c6GlzXXN73HV3FQC9MqFxTKlHilzLTs1H0mjm3d922v710Uz16XaaSxNfgwBFqGKclTXXNNUEfZlbcfG39lT8UyVXYbcugL2j0o/pR+HaPeFZSRvp3VKpwyvov1zS3YRYjyX4rGgIiIDt4TRHEZ4oR1ySNb3XPWtH5W60UkEFGzYCdRA3MYNLR5n4VC8kuHfKqx0xGynjJHtv6I8tfguPNcUua8Vkhgbq5siMeqxrNjnE7hqLvFUb3MNRqVws8RWSqYbh8mJyNihYXvcdgH5ngO1bZk3KUeXI7mz6hw6b+H2WcB+a58p5Ziy3Fpb0pXAa5LbXHgODexTqrKWTz7y9dTww8v7CIioecEREAREQBERAEREAREQBERAEREAREQHQxPBKbFRaeBknaW2d8Q2qoYryXU89zTyvhPB30rPOxHiVfkUps707irT8sjEsV5Pa6guWsE7RviNz8JsT7rqr1FO+mcWyMcxw62uaWke4r0quKemZUW1sa+x2amh1u66spm6n2pJedZKpyXYWcPog9ws+oeX7Rt0dTP1P3lPYHgcOCNc2IEue4ue9x1Pe7tKkkVWzBVrSnKT6hERQcQiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiID//Z",
			dates: [new Date("2022-05-01"), new Date("2022-08-01")],
			colorClass: ["border-cyan-400", "dark:border-cyan-600"],
			bullet_points: [
				"Implemented features and fixed bugs for InfluxDB, the open-source time series database.",
				"Built a new InfluxQL shell with features like fancy tables and command autocompletion.",
				"Designed a proof-of-concept visualization for geo-temporal data on a 3D globe.",
			],
		},
		{
			title: "Machine Learning Intern",
			company: "VPI Technology Group",
			image_url:
				"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPEBAQEBASFRUVFRUQEBUVEA8VEA8VGhgWFxcXGBcYHyggGB8xGxUYITEiJSkrLjoxGB80ODMsNykvLisBCgoKDg0OGxAQGi0iICUtLS8uKy43Li0tNy8tLS0tLSsrLTc1NS0tLjAtLS0tNy03Ny0tLTAtLS0tLS0tKy0tLf/AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABAEAACAgACBgcFBQcCBwAAAAAAAQIDBBEFBiExQVESEyIjYXGBBxRSsdEyQpGh8BYzU2Kj0uGiwSQ0cpKywvH/xAAaAQEAAgMBAAAAAAAAAAAAAAAABAUBAwYC/8QALBEAAgIBAwMBBwUBAAAAAAAAAAECAwQREjEFE0FhFCEiUnGRsTJCQ4Hw0f/aAAwDAQACEQMRAD8AvEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFea0aX0jgrnHrs65Zyql1VW1cn2d6zON+2eP/jf06v7SytPaJhjKZVT374Sy2wlwa/XMpzHYSdFk6rFlKLyaLfE7VsdHFaooM9XUz1jJ7X/tDs/tnj/439Or+0ftnj/439Or+0j4Jfs9Xyr7ED2q7539yQftnj/439Or+0ftnj/439Or+0j4Hs9Xyr7D2q7539yVaL13xUbYO+anXnlNdCCeXNZLhyLNptjOMZRaaklKLW5p7UyiCdez7T/Rawlstj20t8HvcPp6+BCzMVbd0FwWPT82W7ZY9deCwgAVRegAAAAAAAxmAZB5QujJtRkm1saTTy88j0BhPUAhutus+JwdnVwqh0ZLOE5OUulz2LLJp/NEQxetWNt33yiuUEofmtpLqw7LFuWmhAu6jVVJxeraLdtvhBZzlGK5tpI4+L1swVW++MnygnP847CpLrpTec5Sk+cpNv8AM8yXHpy/dIgz6vJ/pjoWLi/aJUv3VE5f9TjFflmcXFa/YuX2FXBeEXJ/myKM85SJEcOqPgiyz75/u0+hd2gdLQxlEbYeU48YS4r9czBWWoOmXh8XCtvsXd3JcOlt6D/HZ6gqsmjtz08F5jZKsrTfJb5EdfNAdfX7xWu8rXaS32Q+q3/iS4Gmux1yUkb7qo2wcZFCAlOvOgPdreurXdWPhurnxXk969fAix0NVisipI5O6qVU3CXgAA2GoH1CTTTTaa2pren6btp8gcmU9PeW5qhp1YyntNdZDKNi58pJcnl8zvlKaD0pPCXRthw2TjwnHZmvyLjwGLhfXC2t5xks0yiy8fty1XDOlwMrvQ0fKNg8r8RCtdKc4xXOUkl+LPHSeFd1M64zlCTXZlFtSi+D2FM6SqthbOFzl04vKXSbb/F+BjGx1c+dD1mZbx0vh11LUxet2CqzzuUnygnLP1Wz8ziYv2iVr91ROXjOSj+SzzK8BYQwK1z7ypn1S6XGiJRi9esZP7DhWv5YZv8A1ZnExelsRd+8vsl4Ob6P4LYaQJMaK48IiTyLZ/qkzr6s6alg71Pa4Ps2x5x5+aLgoujZGM4NOMkpRa3NPcUQTj2fawdB+6WvY3nS3918Y+vDxz5oh52PuW+PgsOm5eyXblw+PqS/WLQ8cZRKt7JLtVy+GXD0KdxNEq5yrmspRbjJcmXsQr2gaA6yPvVa7UV3qX34fF5r5eRHwsjY9j4ZK6lidyPcjyvwVyAYky5OfMSZr2zPqyZp2zzCNsUbuhZN4vDZb+uqy8+nEwdP2fYB36Qp2bK++m+XR+z/AKnH8wVmbcoz00TLjEx9Yal4gAqi4NTSWChiKp1WLOMlk+a5Ncmt5TemNGzwt06Z719l8Jx4SRdxHdctA+909KC72Gbh/OuMf1xJmHkduWj4ZXdQxe7DdHlFTAy01sfkzBeHNgAAwCWah6f6izqLH3dj7Le6uf8AsmRMGu2tWRcWbqbpVTU4l9kQ190B19fvFa7ytdtLfZD6o9NRdP8AvFfU2Pva1x32Q4PzW5krKL46LPVHTfBlU+jKEBKNeNAe7W9bWu6sezlXPjHy4r/BFy9rsVkVJHMXVSqm4S8AAGw1AzGTTTTya2pren/sYAM8Ft6n6dWMpyk+9hlGxc+UvX55nfaz2FKaF0pPCXRuhw2SXCceMS5MBjIX1wtrecZLNfR+JR5eP2parhnS4GV3obZcoq3XTQLwl3Sgu6sbcOUHxj9PDyIxOReemNGwxVM6Z7pLY+MHwkijdM4SzDWzpsWUovJ8pLg14Mn4V/cjtfKK7OxO1PdHhmnbYeD5Le9iQkydezDVrrrPfbo9iDypTX25r73kvn5Em61VwcmeMahzkiX+z/Vv3HD9Kxd9blKznBfdh6Z7fFswSwHO2TlOW5nRQgoR0QAB5PQAABXHtA0B1cveq12ZPvUvuy+L1+fmQovbE0RshKE1nGScZJ7mmU7rHoeWDvlW83F9quXxR+qLjByNy2S5Rz/UsTZLuR4f5OWACwKkAAA2NH4ydFkLa3lKLzXJ80/Bly6F0nDFUxthx2SXGEuMWUkSDU/Tzwd2Un3U8lYvhfCXp8iFmY/cjuXKLHp+V2p7ZcMtHSeBhiKp02LOMlk+afBrk0ym9L6Onhbp02LbHc+E1wki7IyTSa47V4ke1z0D73T0oLva83D+dcY/TxIGJkdqWj4ZaZ+L3obo8oqcGWstj9TBeHNgAAwGyVaiaw+729Ra+7sext7K58/J/Qicma9szXbWrIuLJGPZKqamj9CkO9ourXvdPXVR76pZ5JbbYb3HzW9evM2PZ5pt4vC9GbzsqfVyfGS+5J+mz0ZKSh1lRZ6o6f4L6/Rn5/1Y0HPSGJjTHNRXatl8EOPrwRfOCwsKa4VVxUYwSjFLckjX0ZoijDO2VNai7Z9ZZlxf+y37PFm+e8nIdz9DGPQql6mQARiQAAAAAAYOPrPoWOMocN049qqXKXLyZ2AZjJxaaPE4KcXGXDKHuqlCUoSTUotxknvTX/w+CwfaDoDpL3uqO1bLkuK4S9OP+CvjoaLlbDcjlMnHdE3FgAG4jgAAFh+z7T/TisJa+1FZ0t/ej8Pp8vInBRFF0q5RnBtSi1KLW9NFwas6ZjjKFNZKa7Nsfhl9GU2bj7Hvjwzoem5e+PblyuPoQ/2gaA6uXvVa7Mn3qX3ZfF5P5+ZCy9sTRGyEoTScZJxknxTKd1i0PLB3yrebi+1XL4o/XgScHI3LY+UQ+pYmyXcjw/ycs+ZMy2eU5FgVkVqfNkzTsnmfdthrykZ4N8I6sn3sgufvOIhwdSk/OMkl/wCbLWKx9jeDeeKxDWzs0wfN/al/6FnFBmtO5nSYa0qRkAEUkgAAAAAAAAAAAHxOCkmms09jXBoqTW/QTwd3ZXdTzlW/h5x9C3Tn6c0XDF0zqnx2xfGEuDJGNe6p6+CHm4yvhp5XBSgPfHYSdFk6rFlKLyf1/A8C/TTWqOWkmnowADJgHV1b0zLB3qxZuL7Nkfijzy5o5QPM4KUXFnuE3CSlHlF7Ye+NkIzg04ySlFrc0+Jy9aNCxxtDhsU49qqXKXLyZEvZ/rB1clhbX2ZPuW/uy+H1+fmWMUNkJUWfg6imyGVV7/PJQeJhKEpQmmpRbjJPemjRusLK9per3Si8ZVHallelxXCfpx8PIq2Ui7x7VbDcUV2PKqewxJn1gMHZiroUVR6U5vopfnm/BJZmvZMuL2aar+6U+8Wx761bE99VexqPg3vfojzk3qqGvnwS8bH3vQkmrmh4YHD14eG3ortS4zk9spfidMA59yberLxJJaIyADBkAAAAAAAAAAAAAAAiGvmr/X1+8VrvK12kt9kPqt/4lZF9lW686A92t66td1Y9y3Vz4rye9epaYOR/HL+ik6nifyx/v/pFgAWhSAAxJgyYcstq2NbV4Fs6lawrGU9Gb72vJWfzrhP6+JUFkz00PpizCXwvre2L7Sz2TjxiyNk4/dh6+Cfh3umfo+S/ZwUk00mmsmntTRR2vurzwF/ZT6mzOVT29nnB+XyLq0fjIX1V3VvOM4qUfU1NYtC147Dzot47YyyTlXNbpL9cWVOPc6Z+/jyX19Ktj7ufBVnsz1Y97u95tj3NT2JrZbZvS8lvfoXOami9H14WmuipZQguiub5t823t9TbPORc7Z6+D1TUq46GQAaDcAAAAAAAAAAAAAAAAAAYNXSOBhiKp1WLOMlk+a5Ncmt5tAJtPVGGk1oykdMaNnhbp0z3r7L4Tjwkv1wNItnXLQKxdPSgu9hm4fzrjF/reVNJZbHv3Mv8a9Ww9fJy2ZjOmzRcPgw2eU5GZyNa6wkmiMdD4uma8pGZSNeyZkk1w8st72Q492YW2pvPqrM4+EZrPL/uUn6k+IB7HtHyrwlt0ll10+x4xgss/wAXL8CfnO5WndlodFj69tagAGg3AAAAAAAAAAAAAAAAAAAAAAAAGCt/aJoDq5PF1LsyffJfdlwl5P5+ZZB5YrDxthKuaTjJOMk9zT3m2i11T3Ij5FCuhtZ+fbrDUlI7WtmhZ4HESqlm4PtVS+OP1W5nAsmdFCalFOPk59UtSal4PmyZ1tTtXp6RxMatqrj27pL7sOXm9y9eRx6KJ3WQrri5Sm1GKW+TZf2p+r0NH4aNSyc32rp/HN7/AEW5EXLyO1HRcssMWjfL38I7GFw8aoRrhFRjFKMUtyS2JI9gCiLhLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4OuGgI4/Dyr2KyOcqZfDLl5Pc/8ABQOMrlXOUJxcZRbjJPfFrevxP02RDWDUWjGYynFSaSX/ADEMv3+X2fLk/DInYmV29Yy4IeRj72pLk43sp1V6qCx10e3Nf8OmvsQf3/N8PDzLIPmMUkktmX5H0RbbXZJyZJrgoR0RkAGs9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/9k=",
			colorClass: ["border-blue-400", "dark:border-blue-600"],
			dates: [new Date("2021-08-01"), new Date("2022-05-01")],
			bullet_points: [
				"Training custom machine learning models to detect trash in rivers using Pytorch & Yolov5",
				"Parsing video streams with ffmpeg & Opencv and generating randomized datasets",
				"Managing concurrent image labeling",
				"Building internal DevOps CLI tools for GitLab project management",
			],
		},
		{
			title: "Marketing Coordinator & Software Developer",
			company: "Neo Home Loans",
			colorClass: ["border-sky-400", "dark:border-sky-600"],
			image_url:
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAApVBMVEX///9DQ0RLyPI8PD1Ly/ZCOjhDNTBNxOxKmrWIiIhDQUFDPTtGU1lGgJZAQEFERUQ0NDVMuNs4ODkwMDHQ0NDw8PBJSUpOTk+vr6/5+fns7OxCNC7Ly8vBwcHk5ORTU1RiYmOkpKTY2NhJjKRIc4NGXGVLsNKAgIGPj5BtbW6ampupqapaWlt2dnZKob9Ie45GV15GZXFLs9ZETE9KnLlGZHBHbnyThrNaAAAHJklEQVR4nO2d61qjMBBAy621sCJCb7TQKq6trbau1/d/tAVplctAAoGS+M35ubuyHAkzkwCTXg9BEARBEARBEARBEARBEARBEARBEARBEARBEARBkN/KPPA8L5h3fRot4fqbiRUzHXpdn03juKOhbSmmFGMqlvIQdH1OTRI8TCxFSqNY04dl1yfWDMHt1Pm+eklMxXm6FV5y+biybEjvKGlbTzOBA894dlOm9y25nbldn2odxv6WrHeStPe+YJKut7Ep9WIUyx6Ouj5rekZDJRc6aSTNoRAZBMoMlIRpcrXjPLguizIDtaTtrB65lRw/PtHGlnJJ+2Y27lomz3hGHTppJK29z5Wk6++rhU4aSXvj8ZJBvI1pNasXo1gSDxlkNDTrhk4yYXCddDsHCXYTttBJI+msuirPw8xgtax3lIwyyNnL8zlNUd2kZFienzG4hkW1c0a9k6RzpvLc9fbK2fWOkpayaX2Bxxu2kxloaTmDBLsWMwMtYQa52rWSQZa71XlCJ5kw7qxumw6uwbbtxFeNKO40mSXdocOTXoziPDQmuDQ7v/tA7GlDQ3XUUXIgY5qNhJyAwxF6wlQauBnHEr+CoeKUvczZ8nkPnlA2rIK+U/4/GFdJdI35lDUpeUDJIP17h7XEWZWPUe0gD5JcLnQmPz1zQPmZpGjesAl6hEvYH8gp1DX5t16C9jFQ08d7J44Khy2e7glhJmsoq4OPfl0/fXGpZg93QTRUmBL/mBRmcobhSd31641U42qdFaQxNCcshiOruqGsvr7VCTj9z0FOkMZQslhy4syuYSir8t/Kl1HXLvJ+lIY+g+FDjVH6dWIHo1rA0f5cQ4JUhvZtB4ZhwLmvMFL1fi7EVDBkCjXDuoaVAo4hHQoE6QyH3RiGqXFCN1JzSVAUw3CkflKkRl27K/Tj3fDr/EgjVXvLJ0GBDGX1+l/5Gfb/qmWCvBmCJ1tWi4d1NpDkk4fhy1C9hEaceiisxbV7IAmqF8nIypnhm9EHokZYi4NnCSbBKDppl9wa/tGlPhT5wdRoTKALvr4yJINrQ8kwoFsrX4vDdfZl9Kvg3DAcfM9yfhKUqcX1PlBnq9dxpce7YVRFv0IBx/hR1P5BIeb9mDz5N4RnQj+pUV88A38dXuXjMQUwLL3LJEMn3KlCGIIrEnGkBOvsVLQVw7A428EZM1miC2JYVLFAF/Cgp6oeYQwl3XgvraqPP6U+Z+oBcQyjmUM+NWYF87MPkQzD2R+QGlOCwAxSKMMw4JTO4GVoFUAsQwmuxY8/sH6DJlaiGcK1+Bd38ORYOMOoFodm/+rdAj6meIYFK9rqoWCZSkRDUi3+CwyjWhxIjSq4TCWWof79RwWrFsAylUiGuvb5kw/A1KgOXnIZUSBD422dWtnX7uFnoNkfE8YwngarFz+FtU6a/AplqGvHmUUqZC6AWjw7uxDEMLXYlAiZYC2efmQshGFmhp9c2S8IOIlHxiIY5h7qhiHz5yL1X8pXagQwhBRSy1Q6mBpPj4y5NwQf6qqD5E+Btfh3YuHdsCCU6OlMAq96x6mRc0NoaUaVs4tNpbU414bfSTB93n+g04SXqcLEwrPhAi7LCp5zw+viB2nBraG8vshfE1XOl9YnCmLSXfK3xpchsFZR8hQ/Aq7FUwOAK0PgCl4SXv0qXqYSwpD4No1U8MhYFEP1wii/gDHgI2MRDBMPdQkUvDzLu6G6rvAqNFiLc25Y8XV2Qyp4f49Xw6LXoIoBPkTg2TD7UJcKMDXyaQjV2TSAj4x5NKRJgkUHy9firRtWf1ef4rXgYvJzy9bf1ScaLtI3D92r3cVEtXj6gOQvu9i+tyB+M6PdXSc5UL6eX3LAj9fUEV/II4Lpmxnid0+SoaVg+/owQq98QKbvnojfrnEA27drvS3PnznHMIXSXs8jDtPOYfyGtDfl/SKyfgfc83m/iA5zT55f/z1+GE55HqfmpIHWUQHhg/UuMe1GmtR4nXaGKsNUGmqnFCh83ov2pLE2Q+6Gww4upsOW6jOMbnhpgxUTNeFruuFXsKvdH7hpTMWattMt0muzkyc1UcfP9prSud7e7rjnnrJpu2vr2N823VGXlvP1bp/PbjrpfXnWBp/z29I9D5rXs58ez94cOthJ5+k0aCpOS6GTQrJ+h3lqwszQTqtLWrxNnV0C6PVMDhpeRxmklVtSiZqWd213pNGW8zFfmYGrxvMNbRtw0rO43DxgedtIl1q+d9dhbtLeZWagZTSsn0GiXa5E2IjF9TaOXWefGYeDzEBL5Q0vTFvZsDxC6gKq7axOetaNaPs9xcxnFBmE18xAS5hByoJrtLkcv1sD0VJYnkfLLbxv70QLtFWLYklCZAZaXH9j2ck9LPkpqpvDne2l4z6kE+EyAy3ucuT7/mgpZGZAEARBEARBEARBEARBEARBEARBEARBEARBEARBEISG/95VyTWQvzTiAAAAAElFTkSuQmCC",
			dates: [new Date("2021-01-01"), new Date("2021-08-01")],
			bullet_points: [
				"Graphic designing for marketing and promotional materials",
				"Created PowerBI & Domo dashboards for data analytics",
				"Built API middleware and Selenium programs",
				"Deployed Docker containers to Microsoft Azure",
				"Filmed and edited promotional material",
				"Built and deployed React web app on Azure",
			],
		},
		{
			title: "Data Analyst & Admin Assistant",
			company: "Fairway Independent Mortgage Corporation",
			image_url:
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAzFBMVEUMlkj///8AlEVQrWn///4HmUsLl0cAkju02cEAlUNSsHgAkDsAlDv//f/8//+t2LxYr3k4qmmm1LcAjjD///sNlUoAkDYAkT8KmEUAjTUAji8AjDIVnlEAkEAAjy35/vtLsnbM59dDqG71/Pdft4Vsu47f8ecAiiWBwZWOyaRvt4YupF/t+vLH6NIAlzmbz7CSy6heuYLG5dXY7t/v/vV4xZQmolQcnFep07aUx6O02cWBwZY0qmVFq3We0rB3vpYAggYAewCLw5g6rGFWRTCJAAAOoElEQVR4nO2dDVfiOBeAm25JiIUilLQpIBVBlK9BZdQdnXF25/3//+m9aVWQJkhrC+2e3jPu7nG6tE9vcr9yEzTtvy36X8d+gqylJCy+lITFl5Kw+FISFl9KwuJLSVh8KQmLLyVh8aUkLL6UhMWXkrD4UhIWX0rC4ktJWHwpCYsvRyDE+KC3OzQh1thhb3h4HdKaSw96wwMTUqd3PZkS54C3PBwh5prmzFZISKPmYg0fZrweUIeMOkuE/LYFiP60Sw9kcQ5FCDT2+RwZbcCz6gC5qLj8IFo8ECHG7rcqQoYBP+Kf8G907dDKAW59AEIsXIR96aNtWc0chlnWY/UQOsSa2xug+jYgDNWlrWc+GQ9BSOyJMC4RHcJonf/yeMZ3PwCh0xyjYP5tiR/8rlpzs719hoScMYyx3mkh1I7obz1S/ZFNNc55VnY1Q0Lwd1zrnwwFxg6po0GFMC0zi5PlKAULQ55eNaXksyz42+c+zSwiz1KHun0vzItyiG5YnPGsk9VjZEbINbO3+oxtQ1oe1SpZ6DErQkz7E4n93CHzczOTtCojQm6Ci6hbu23MhrTFXK3SWgaPkg2hW2uB/vbmexP/0tZTf5a0CTmEKLQ7Gip1BT+GoRy9i0dHxLFpeo60CcHLE3oXDULfBegsNSFCky7MxjQtTsqEDCzMJWBYlpwxDE4NpQMB9PHMSTVUTZvQeVwBn1pFaLD80VKN4YDRQi8mSfGRUiSE2aPbN8pHt0SAtprZJiHdqQ+jtY3q0ldhofmJrWGe0mxMU4fYac4VBlQMWhiB91cc5hhEc7WqOpYz4NonTsR1aUiKhMRtiMdWzDHguYPHDvINTHX7ZK7Wdlu8DFtcmMJjpUaod2+/v5LI+axbm2LMOQ6zKmq/KEJWwLPgZ8XNVLSYDiHWCFuodYLqBmo52zGZPRuLEal2LBOPpmBVUyBkFbAwz2oXJxz8+MKMPCyD/ytUl0rGTQ9/WY8pEHJOHsc7kkBQ0sSW1H8hQa5VFmodiiHcMulXvX8KhK4DLsJXDzY06JmaLrEakPXSjjLACyqryB91vhiqfoVQlCmw1hWlbPkjglGEGO1yRzkNa1Q4DkNlg+uiOG5yXsGJ6+NfIoQf02kghedGwchdUMp324uw2t+We39IwNq/u5QxLanR+QKh8Ff2rY/g4ZRDdHhqc6HoXR/DqL0Ea6uyOMC4erSTG9UvzUPC78QIq8tHKQw7cBGB21YiwuATf+88qAoe7XDw3ji1g49ShsHYK+2nBXMQjP3eK6G6dx9aFpWMmzYY7SSeIyEhDBrSG6stvUgvJnaMogQ38SKISOXii/HgJvKNSXVIzZdd77wOLuIMa3uvnsFYpd1RdGnj/Y3Bnb6PuklKVQkJhf2zdgwq61LUP/d/5ViULlzSUBIGfxY8wRpHAkLMaq46+QlKFNUaSTSivOY4HAEqubd18TbiWJ0EhNSBOET1EAZkPpDAJo1DiHkTfobi9aHVg8vixaoJCLvVwElJpQ3GAlxE8qVdiHF3VcrhxZ5SLZb3j09oTkQ+oEgJfLF0LdacEiav4A/0/m+1xRHB3QPG2RIS1d0D0/rsfbmmy0TGsSOnuuvGGiAxCblG75Xv1wAXQdKoBOr26TBI9eU3IrHCm5iEVCN/K1+uPxUW5svVXFGsqjlBzUeO2NQzHKWYOS0VYIO6OI3eSiamGXdCxyEljOX44xJiM0JYD172/Lwb65M+FSo6OIy2JG/MVocSwuARXrw069ThvcjjQLoE2YzVhJMCIQq6mxLF/TsFJnT/0pfq8OCENx09no/a717w43KJ/z88YcuO9RmxRO9Hy3gHJxw66evvTahGL45PuIwWe1MTzrR+pJR3cMKpnl0nLKQRThVtVakOTniabT+z2dh2GSXhRykJt6QkjCNMBPKYi2z5tWgsquh6KK9XQKREGtu9G4Uh5BgzyJSY7po1x/E8h/BKpRdIhXPidO1O/8x17ca2Q8yY0I3kh4l1iCkxPVJpTn+0nu7Gwy2/7s/Hi6eXyf3F0/YNsyaM1DSTEOq66fV7o+XT6r0mI+aaPONtH3QeaqSamLAiQhTMdUpsfLK826exz5D1wOWWEGuMY+p6ZPS3Mn3fFOUbyC0h2E1i934EPRvt7Uhsl2zrMbeExOndCOUZ7fcn3rH4L8Qa+kP4s10+zbaKkYBQOD1NN+mzqphtGci33pdZ/fFT62Z62nzklIAXAanVSG92cfs8aT2NRSfVRaxc5hCEkKr3m4EJVhezA9JV4/mi0rE9k7pUf+/5YoxpOkQC1BRekz7cPmRaa0sySr85l2J0qtZbgt/Pq88zx+4QKlrCOMfBcpuucdMkxPO8bte2baFPYppn8XxT9oQmmQxh7lmyrU+hGIvnB888o+GqmfgsRl3i2E7l5+h5+ffTYrAaB7K6qzaWf0aVWAsHGRIGWnDMpdTqt8GaBi0cw6dziNrEM4d6w7pLuvbs8qU6Vo3pE5obW4pd80aut3pYsbeqJ7bzqrsg7qam17tshO7SUPUa54ew5lwPFR4hePbVM3V0xt+W4uiZV7luzDevkL+evBDq9q/A+4lHlVFWm2AzgzMWRDewbtqzl8CdCG8p/lg5JsSswrDJIzlBoJrw2a0X7IRzT1yuE2+2/NAzHMYERth+sh3THJ1QlL/17qUVNKVFCOuC8eabid8u1nSHi2DgA4X1OkyHq8afu/zpkFNaGcgj5+B3y5pY4wysC8O1zqzxrrS1DpFwkfePxCP9xvYnHZ+QOtOApR1dVIEnb2Cii17vIPSi9u2b+j4i3v3p2cSFeYqdxjb+cQnhvyhRtHyLFqPBzAn9tfANZ/ZoK48K88HBdc0jb249Wok6KiHD2remoqMWfunfOmFXE64wpndHcxQdzP6y199sfcoZIa50fssVKKRBCHtbAOCdCxifvr/u1gtQx79twj90bOaMULNFT7O8o3YoWqXe9hc4vbehvPn046ldY7zCNvsBckQISQEhkhzQCtOHp2+vSQ+4eBrZHyUcy/CyI8mLckSINfo4lPR811Ed0tvbjWVUO7I/SiDceET25Dki1M5mvmhJj+rQQque+f5U1G5J9ketHk35LXNESC6EO4jOwaDfm63n1WyM6sZ2c+qz2AEkXUvOCSHDvHYii5QDkvug1Uak7xq3r7cvEftGH86UHZU5IaSMnMsAxS4K/+I9COX6WeR/h3ladZm6ozIfhBo2L6ReAh5tXnFfz0qAIKY3386kwIj+trGm7orNA6EOOpwFwbNkZ8/KfTNEmJ+dI4miT0DFO7o58kAIRr7iS1IJcVDCwg59Ja1g5n1s3AzKGMj/+Ul3eg4IT2ASzlFbYkPbqNEPu11Fkak72bpAuE7r0+JnDghP9f4AWZKdWW3U6rBwW5c4b6+13TptWfVh79Pqbh4IOy1kSfY+Wajlaa+ZLtY6je1ZKszsI/20Kz0HhBcnEe3BAIScodEN5yCku+xK5iXQbI/6fA4IT32pp4c5+L4piHYipQixiPFrn41ROSCcS9YCfQRW9HVXJGR7zousavPb2edJc0BoWNHidBsNuvh1ijHNnsh2ge3ZtJkDwgid2A86XuuHkcvINXUDrfY8+yqHhGKMDjeCFIhYo/PUMNieK0i5JBQbBt6zJb0nmYIGut13o10eCS10W1ufoSs6YKOMVW/fp8whoYFuNvb/etHiKaQT/v4bl3NIiAYbRtKJFhfF4wol73nLHBIOydrM0Kb0kkWX770/KoeEP+laP57knB3wJTO6/+k6+SO8fquZYc5kwRo8bkNRVpNK7ggH3fW1dCTf8B2rmSJnhIa1sf9JJ0MkK09V+3FumTNCNFoPQLHyZ8kWSnuxdoHliVBsxO+8XadhuR31wdnH2sdLIl3QxyNso++UszdPgT1ZFyk8a9ONRWhGmpKPRmgZaFRbr/u5E/mu/ZXNY50YED1K4ojz8K4jXERwHda+WbKzStromcbbK+xJintHImyjtQXhzJGe4gGJcKxv74Axbw/zMw8nG9+vQnuKi57ieHuNYxqtcx2NcO68WxmNm/J+jDY8Xpz7MWpG476jEZ5stF/jmeKESMuJE8/opDJGkdNej0JobIRrokvUvlN03TVqnPPavvKwlO3lPo4ODfSgv1+D9ZlCz7GPh5YdonIUQgtV7fU12FEeThJ8D8u+YskP4zkKYXszX8CBIVUdZLr3Meb1sEUxL6P0Zd0pgjW5L0xNgFDEfTo1bcc7o5jtjCDSItyou2CdZwoY6hBzZzoY+uOXyieHbqVE+ELWdRdsbi+Fpk/Imc7GaF4VTe+37s6aTyqEFtpsbWPOMM53IiQi1Fj/Oxr9c3X1zy8fnbrZj9LWZihWu/1sx9bXCRlZotPeYLBq9WfIJ7vipFTWnlBvM1DpDGJ9r0UiQo1AhPGAqhO0vKqi37vOxkmDELL2zU+sxPvmjkSEvIl+mA/o8l+08M7R0658JQXCOpptqtBcfrJFLQ3Csymakke0WsEkfECDXflKEsLts5s2VwKxZqsPW09JmjrWL9Af5xE1Vqsr9j+0SFGH4Ar+RE4Zu9XXp3hyep4k+owlBGNMYHg+oOcRmnZakJimRyj2Km+fjDzsb7gjvt/6YnKxhMaCEsLPynh6NWg4BtqZcsYnJNvfAfRirjNfzPoZT0KEeiJko9y3ZlcOvaqN0XWahEK6L+u7iYO4P9R3a5LmmhTFQP6FGJJwy94c3f3584TQxNl5AlCSM2jN08HGMF3ZG7Uz7GY7SIcvlUBhIsuu3QibtmimG5cKYZja4pCOV+GbJ6YyXMlSdNN9L5Vg6jo17Jn6J19mkuSUXfGJuq6JM1ao9vF7NsTt9ewEv71MFuyGFhsgIAhPnbBgUhIWX0rC4ktJWHwpCYsvJWHxpSQsvpSExZeSsPhSEhZfSsLiS0lYfCkJiy8lYfGlJCy+lITFl5Kw+FISFl9KwuJLSVh8KQmLLyVh8aUkLL6UhMWXkrD4UhIWX4Aww77sXMhf2l//cZn+HyKRFgECzwLGAAAAAElFTkSuQmCC",
			colorClass: ["border-emerald-400", "dark:border-emerald-600"],
			dates: [new Date("2020-06-01"), new Date("2021-01-01")],
			bullet_points: [
				"Automated CRM data transfer and form-filling using Python (Selenium package)",
				"Automated creation of gifting order spreadsheets using Python (exchangelib and pandas packages)",
				"Built dashboards in PowerBI analyzing loan operations volume and performance",
				"Built reports through Encompass LOS",
				"Assisted in new technology adoption and IT needs",
			],
		},
		{
			title: "Software Engineer (Contract)",
			company: "University of Utah - Genetics Lab",
			colorClass: ["border-rose-400", "dark:border-rose-600"],
			image_url:
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOsAAADXCAMAAADMbFYxAAAAY1BMVEXMAAD////JAADz1dXuwMDxy8vROzvZaGjjlJT55+frtLTHAADVTk7aa2vSPj7y0tL++fnYYWHPKCjQLS3RNjbTRETUSUnVUlLXWlrcc3P67u7ijY3NFxf23d389PTOHh7deXkzXNt8AAACzElEQVR4nO3d3VJaQRBFYXoMEhUUEAWNJnn/p4yxcsf56Zmme2bi2tfWWf0V3ljWKRbydbaofUDgPqw3VzF7GOpvH4Lir5/WH3cpZHdD1puo+O2n9XtahCwNWqPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yWIPiWN1yX8g68u5gTPyf9Xa3OttmbXry2+b8kavTkPX1NPCTGyPseP7I3XL8Xd+l6cO+H3mqdrbftDT4pu249Zspd13XusSKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsWKFStWrFixYsXarvXwfmXZu4kabF0k27qyVh1WrFj7GVasWPsZVqxY+xlWrFj7GVasf/fzrfbF5dtv86yy/VX75NLtx0ij1m6xj6OicWun2HHqlLVL7AR10irbfe3Tc3eY4kxaRTrDTlLnrF19smmaOmcVeawtUG+OOm/tBptm/xE6b+0Em+a/n0hhlUNth2IKqsraATY9KRgqqxwa/6tHRVVa5bpprI6qtTaNTc86g9Yq981itVS9tVlsWmsFeqs8NYnVU3OsTWIzqFnWBrHpmHF+llWeG8NmUTOtjWHzqLlWWTeETYPfsno5a0PYXGq+VY6NYLOpBdZGsGmXfXiBtQlsAbXI2gC2hFpmlVNlbBG10FoZm1ZFRxdaq2ILqcVW2VXDpk3hycXWathiqsFaCZteig82WGVVAWugmqwVsBaqzRqONVGNVtmEYm1UqzUUm37bbrVa5SUMa6XarWFYM/UC1g9syMzUS1i7Gdb/c38AbI1hoyuPVwIAAAAASUVORK5CYII=",
			dates: [new Date("2020-05-01"), new Date("2020-07-01")],
			bullet_points: [
				"Worked as a software developer for a genetics research lab",
				"Wrote backend software in Python using the Flask framework with connections to an SQLite DB",
				"Significantly reduced false conflicts in the Clinvar Miner genetics database",
				"Worked with Linux server hosting",
				"Efficiently found closest common condition from sets of conditions from the Mondo Disease Ontology",
			],
		},
		{
			title: "Data Visualization Intern",
			company: "BrainStorm Inc.",
			colorClass: ["border-yellow-400", "dark:border-yellow-600"],
			image_url:
				"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ892BvOyWHhb4dDGu2-CzIRwmuO6TJf4SP4B60gyGLX2iMEnGXuso5kCxE48VEf8Hal5k&usqp=CAU",
			dates: [new Date("2020-05-01"), new Date("2020-06-30")],
			bullet_points: [
				"Developed data dashboards using PowerBI and PowerApps",
				"Integrated Microsoft semantic analysis on data using Python and PowerBI",
				"Worked with databases and data services like Snowflake",
				"UI/UX dashboard design experience",
				"Created screen capture videos for training purposes",
			],
		},
		{
			title: "Software Development Intern",
			company: "Red Pepper Software",
			colorClass: ["border-red-400", "dark:border-red-600"],
			image_url:
				"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThIJV8WvvqHPlpiG0osF8OqszhQyF83Z3uerK7zKTSxwOGvYvjdYHWxi5G_b0COkmnp4g&usqp=CAU",
			dates: [new Date("2019-03-01"), new Date("2019-08-01")],
			bullet_points: [
				"Full stack web development experience with SQL databases, C# .NET Core backend, and REACT and Vue frontend frameworks",
				"Maintained various projects for multiple clients",
				"Created unit tests for new features",
				"Built and redesigned features",
				"Fixed bugs",
				"Worked using the AGILE framework using Jira",
				"Worked with REST APIs",
			],
		},
	];
</script>

<svelte:head>
	<meta
		name="description"
		content="Hello, I'm Andrew Lee! I'm a software developer and student at the University of Utah. View my work experience here."
	/>
	<title>Work - Andrew Lee</title>
</svelte:head>

<div class="flex flex-col items-center -ml-2">
	<article class="prose max-w-none">
		<h1 class="text-center mb-8">⚒️Work</h1>
		<div class="mt-14">
			{#each workEntries as entry}
				<EntryComp {entry} />
			{/each}
		</div>
	</article>
</div>
