// app/components/image.tsx
export function Image({
	src,
	webp_src,
	alt,
	className,
    imgClassName,
}: { src: string; webp_src?: string; alt: string; className?: string, imgClassName?: string}) {
	return (
        // <div >
		<picture className={className}>
			{webp_src && <source srcSet={webp_src} type="image/webp" />}
			<img src={src} alt={alt} className={imgClassName} />
		</picture>
        // </div>
	);
}

// src/components/Image.svelte

<script lang="ts">
    export let src: string;
    export let webp_src: string;
    export let alt: string;
    export let className: string;
    export let imgClassName: string;
</script>

<picture class={className}>
    {#if webp_src}
        <source srcSet={webp_src} type="image/webp" />
    {/if}
    <img src={src} alt={alt} class={imgClassName} />
</picture>
